module.exports = [
  {
    "id": 1,
    "name": "Master Sword",
    "cssClassName": "master-sword",
    "attackPowerBase": 30,
    "attackPowerBonusMin": 0,
    "attackPowerBonusMax": 0,
    "attackPowerBonus2Min": 0,
    "attackPowerBonus2Max": 0,
    "durabilityBase": 40,
    "durabilityBonusMin": 0,
    "durabilityBonusMax": 0,
    "durabilityBonus2Min": 0,
    "durabilityBonus2Max": 0,
    "throwDistanceEffect": "Beam (all hearts)",
    "throwDistanceBase": 50,
    "throwDistanceMin": 0,
    "throwDistanceMax": 0,
    "availabilities": [
      "Korok Forest (main quest: The Hero's Sword)"
    ],
    "description": "The legendary sword that seals the darkness. Its blade gleams with a sacred luster that can oppose the Calamity. Only a hero chosen by the sword itself may wield it."
  },
  {
    "id": 2,
    "name": "Tree branch",
    "cssClassName": "tree-branch",
    "attackPowerBase": 2,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 2,
    "attackPowerBonus2Min": 3,
    "attackPowerBonus2Max": 4,
    "durabilityBase": 4,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 1,
    "durabilityBonus2Min": 2,
    "durabilityBonus2Max": 2,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 4,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Field",
      "West Necluda (cut small trees/shrubs)"
    ],
    "description": "Wooden branches such as this are pretty common, but it's surprisingly well-balanced. It doesn't do much damage but can serve as a weapon in a pinch."
  },
  {
    "id": 3,
    "name": "Torch",
    "cssClassName": "torch",
    "attackPowerBase": 2,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 2,
    "attackPowerBonus2Min": 3,
    "attackPowerBonus2Max": 4,
    "durabilityBase": 8,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 4,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 3,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Great Hyrule Forest",
      "Hyrule Field",
      "Inside the Tech Labs"
    ],
    "description": "This torch will stay lit once ignited. If you put it away, the flame will be extinguished until you light it again."
  },
  {
    "id": 4,
    "name": "Soup Ladle",
    "cssClassName": "soup-ladle",
    "attackPowerBase": 4,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 7,
    "durabilityBase": 5,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 1,
    "durabilityBonus2Min": 2,
    "durabilityBonus2Max": 45,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Field",
      "Tabantha Frontier (by cooking pots)"
    ],
    "description": "A kitchen implement often used for serving delicious soups. It was carved from the wood of a sturdy tree, so it actually packs quite the wallop."
  },
  {
    "id": 5,
    "name": "Boomerang",
    "cssClassName": "boomerang",
    "attackPowerBase": 8,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 15,
    "durabilityBase": 18,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 20,
    "throwDistanceMin": 0,
    "throwDistanceMax": 0,
    "availabilities": [
      "West Necluda",
      "Faron Grasslands"
    ],
    "description": "This throwing weapon was originally used by the forest-dwelling Koroks. Its unique shape allows it to return after being thrown."
  },
  {
    "id": 6,
    "name": "Spring-Loaded Hammer",
    "cssClassName": "spring-loaded-hammer",
    "attackPowerBase": 1,
    "attackPowerBonusMin": 1,
    "attackPowerBonusMax": 1,
    "attackPowerBonus2Min": 2,
    "attackPowerBonus2Max": 2,
    "durabilityBase": 80,
    "durabilityBonusMin": 9,
    "durabilityBonusMax": 17,
    "durabilityBonus2Min": 18,
    "durabilityBonus2Max": 41,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Kilton's Shop"
    ],
    "description": "This strange hammer is one of Kilton's specialties. Being struck by it doesn't hurt much, but the fourth swing in a string of attacks will send the victim flying."
  },
  {
    "id": 7,
    "name": "Traveler's Sword",
    "cssClassName": "travelers-sword",
    "attackPowerBase": 5,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 8,
    "durabilityBase": 20,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 3,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Field",
      "West Necluda"
    ],
    "description": "A very common sword often kept by travelers to fend off small beasts. It's fairly durable, but a bit unreliable against monsters."
  },
  {
    "id": 8,
    "name": "Soldier's Broadsword",
    "cssClassName": "soldiers-broadsword",
    "attackPowerBase": 14,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 11,
    "durabilityBase": 23,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 3,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Gerudo Desert",
      "Tabantha Frontier"
    ],
    "description": "A sword brandished by the soldiers who once protected Hyrule Castle. Its durable blade is well tuned for slaying monsters."
  },
  {
    "id": 9,
    "name": "Knight's Broadsword",
    "cssClassName": "knights-broadsword",
    "attackPowerBase": 26,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 9,
    "durabilityBase": 27,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 8,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Gerudo Desert",
      "Tabantha Frontier"
    ],
    "description": "Knights of Hyrule once carried this sword. These days it's the weapon of choice for seasoned adventurers thanks to its ease of use and high attack power."
  },
  {
    "id": 10,
    "name": "Royal Broadsword",
    "cssClassName": "royal-broadsword",
    "attackPowerBase": 36,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 12,
    "attackPowerBonus2Min": 13,
    "attackPowerBonus2Max": 24,
    "durabilityBase": 36,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Tabantha Frontier",
      "Akkala Highlands",
      "Hyrule Castle"
    ],
    "description": "The Hyrulean royal family would award this sword to knights who achieved remarkable feats. A sword that balances strength and beauty as elegantly as this one is a rare find."
  },
  {
    "id": 11,
    "name": "Forest Dweller's Sword",
    "cssClassName": "forest-dwellers-sword",
    "attackPowerBase": 22,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 8,
    "durabilityBase": 27,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 14,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Great Hyrule Forest",
      "Hyrule Field"
    ],
    "description": "Koroks made this sword for Hylians. It's made of wood, so it isn't the best choice for head-on attacks. Its original intent was likely clearing vines to forge paths through forests."
  },
  {
    "id": 12,
    "name": "Zora's Sword",
    "cssClassName": "zoras-sword",
    "attackPowerBase": 15,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 12,
    "durabilityBase": 27,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 14,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Lanayru Great Spring",
      "East Necluda"
    ],
    "description": "The ornamentation that adorns this blade is a traditional Zora design. It's forged from a very durable and rust-proof metal."
  },
  {
    "id": 13,
    "name": "Feathered Edge",
    "cssClassName": "feathered-edge",
    "attackPowerBase": 15,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 12,
    "durabilityBase": 27,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 14,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Tabantha Frontier",
      "Hyrule Field"
    ],
    "description": "Rito craftsmen forged this lightweight, double-edge sword so Rito warriors could soar into battle unhindered by its weight."
  },
  {
    "id": 14,
    "name": "Gerudo Scimitar",
    "cssClassName": "gerudo-scimitar",
    "attackPowerBase": 16,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 8,
    "durabilityBase": 23,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 12,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Gerudo Highlands",
      "Gerudo Desert"
    ],
    "description": "This common sword is often carried by Gerudo women for self-defense. Its short, curved blade is easily recognized."
  },
  {
    "id": 15,
    "name": "Moonlight Scimitar",
    "cssClassName": "moonlight-scimitar",
    "attackPowerBase": 25,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 6,
    "durabilityBase": 52,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Gerudo Highlands",
      "Gerudo Desert"
    ],
    "description": "Delicate Gerudo carvings decorate this curved sword. The engraved blade is extremely sharp. Apparently it once served ceremonial purposes in festivals."
  },
  {
    "id": 16,
    "name": "Scimitar of the Seven",
    "cssClassName": "scimitar-of-the-seven",
    "attackPowerBase": 32,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 10,
    "durabilityBase": 60,
    "durabilityBonusMin": 6,
    "durabilityBonusMax": 12,
    "durabilityBonus2Min": 13,
    "durabilityBonus2Max": 30,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Reward for clearing Divine Beast Vah Naboris dungeon"
    ],
    "description": "A famous sword once beloved by the Gerudo Champion Urbosa. It is said that when Urbosa swung this sword in battle, her movements resembled a beautiful dance."
  },
  {
    "id": 17,
    "name": "Eightfold Blade",
    "cssClassName": "eightfold-blade",
    "attackPowerBase": 15,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 12,
    "durabilityBase": 26,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 13,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "West Necluda",
      "Lake Hylia"
    ],
    "description": "A single-edged sword traditional to the Sheikah tribe. Forged using ancient technology, it just may be among the sharpest conventional weapons ever made."
  },
  {
    "id": 18,
    "name": "Ancient Short Sword",
    "cssClassName": "ancient-short-sword",
    "attackPowerBase": 40,
    "attackPowerBonusMin": 7,
    "attackPowerBonusMax": 14,
    "attackPowerBonus2Min": 15,
    "attackPowerBonus2Max": 27,
    "durabilityBase": 54,
    "durabilityBonusMin": 6,
    "durabilityBonusMax": 11,
    "durabilityBonus2Min": 12,
    "durabilityBonus2Max": 27,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Akkala Ancient Tech Lab"
    ],
    "description": "The blade of this sword was made using an ancient power lost to this modern age. Its blade appears only when drawn, and its cutting power surpasses metal swords."
  },
  {
    "id": 19,
    "name": "Rusty Broadsword",
    "cssClassName": "rusty-broadsword",
    "attackPowerBase": 6,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 10,
    "durabilityBase": 8,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 4,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Field",
      "Eldin Canyon",
      "Hyrule Castle"
    ],
    "description": "A rusty sword used ages ago by a skilled swordsman. It can do some damage in the right hands but also breaks quickly."
  },
  {
    "id": 20,
    "name": "Royal Guard's Sword",
    "cssClassName": "royal-guards-sword",
    "attackPowerBase": 48,
    "attackPowerBonusMin": 9,
    "attackPowerBonusMax": 16,
    "attackPowerBonus2Min": 17,
    "attackPowerBonus2Max": 33,
    "durabilityBase": 14,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Castle"
    ],
    "description": "A Sheikah-made replica of the sword that seals the darkness. It was made with ancient technology to oppose the Great Calamity, but its low durability made it inefficient."
  },
  {
    "id": 21,
    "name": "Flameblade",
    "cssClassName": "flameblade",
    "attackPowerBase": 24,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 9,
    "attackPowerBonus2Min": 10,
    "attackPowerBonus2Max": 19,
    "durabilityBase": 36,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Coliseum Ruins",
      "East Necluda"
    ],
    "description": "This magical sword was forged in the lava of Death Mountain. It leaves white-hot flames in its wake when the blade glows red."
  },
  {
    "id": 22,
    "name": "Frostblade",
    "cssClassName": "frostblade",
    "attackPowerBase": 20,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 16,
    "durabilityBase": 30,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Gerudo Highlands",
      "Coliseum Ruins"
    ],
    "description": "A magical sword forged in the frigid mountains of the Hebra region. When the blade glows blue, enemies struck by it will become frozen."
  },
  {
    "id": 23,
    "name": "Thunderblade",
    "cssClassName": "thunderblade",
    "attackPowerBase": 22,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 18,
    "durabilityBase": 36,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Coliseum Ruins",
      "West Necluda"
    ],
    "description": "A magical sword forged and refined by lightning from the Hyrule Hills. When the blade shines with a golden light, it will electrocute enemies struck by it."
  },
  {
    "id": 24,
    "name": "Goddess Sword",
    "cssClassName": "goddess-sword",
    "attackPowerBase": 28,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 10,
    "attackPowerBonus2Min": 11,
    "attackPowerBonus2Max": 17,
    "durabilityBase": 45,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 23,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Unlocked by corresponding amiibo"
    ],
    "description": "A sword said to have once belonged to a hero from the sky. Its blade houses the fire of the Goddess. When wielded, a strange yet heavenly breeze kicks up around you."
  },
  {
    "id": 25,
    "name": "Sword",
    "cssClassName": "sword",
    "attackPowerBase": 22,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 14,
    "durabilityBase": 27,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 14,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Unlocked by corresponding amiibo"
    ],
    "description": "A sword once wielded by a hero in an ancient age. When grasped, a strange sense of nostalgia washes over you. Take it when going alone would otherwise be dangerous."
  },
  {
    "id": 26,
    "name": "Sea Breeze Boomerang",
    "cssClassName": "sea-breeze-boomerang",
    "attackPowerBase": 20,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 7,
    "attackPowerBonus2Min": 8,
    "attackPowerBonus2Max": 12,
    "durabilityBase": 20,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 10,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 20,
    "throwDistanceMin": 0,
    "throwDistanceMax": 0,
    "availabilities": [
      "Unlocked by corresponding amiibo"
    ],
    "description": "A boomerang said to have been used by a hero who traveled the Great Sea. It smells faintly of salt water."
  },
  {
    "id": 27,
    "name": "Boko Club",
    "cssClassName": "boko-club",
    "attackPowerBase": 4,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 7,
    "durabilityBase": 12,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 6,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Field",
      "West Necluda"
    ],
    "description": "A crude Bokoblin club made to clobber small prey. It's essentially a stick, so its durability is low."
  },
  {
    "id": 28,
    "name": "Spiked Boko Club",
    "cssClassName": "spiked-boko-club",
    "attackPowerBase": 12,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 11,
    "durabilityBase": 14,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Faron Grasslands",
      "East Necluda"
    ],
    "description": "A reinforced Bokoblin club made to maximize damage. The sharpened bones jabbed into it make it a brutal weapon."
  },
  {
    "id": 29,
    "name": "Dragonbone Boko Club",
    "cssClassName": "dragonbone-boko-club",
    "attackPowerBase": 24,
    "attackPowerBonusMin": 7,
    "attackPowerBonusMax": 13,
    "attackPowerBonus2Min": 14,
    "attackPowerBonus2Max": 26,
    "durabilityBase": 18,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Ridge",
      "Necluda Sea"
    ],
    "description": "This Bokoblin club has been reinforced with fossilized bones to maximize clobbering potential. Only the brawniest of Bokoblins can manage its immense weight."
  },
  {
    "id": 30,
    "name": "Lizal Boomerang",
    "cssClassName": "lizal-boomerang",
    "attackPowerBase": 14,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 9,
    "durabilityBase": 17,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 0,
    "throwDistanceMax": 0,
    "availabilities": [
      "Lake Hylia",
      "Lanayru"
    ],
    "description": "A curved sword favored by the Lizalfos. It can be used to attack directly or can be thrown like a boomerang."
  },
  {
    "id": 31,
    "name": "Lizal Forked Boomerang",
    "cssClassName": "lizal-forked-boomerang",
    "attackPowerBase": 24,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 11,
    "durabilityBase": 23,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 12,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 0,
    "throwDistanceMax": 0,
    "availabilities": [
      "Gerudo Desert",
      "Tabantha Frontier"
    ],
    "description": "Blue Lizalfos in particular like this weapon. It has one more blade than the Lizal boomerang to give it additional cutting power, and it still returns when thrown."
  },
  {
    "id": 32,
    "name": "Lizal Tri-Boomerang",
    "cssClassName": "lizal-tri-boomerang",
    "attackPowerBase": 36,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 12,
    "attackPowerBonus2Min": 13,
    "attackPowerBonus2Max": 24,
    "durabilityBase": 27,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 14,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 0,
    "throwDistanceMax": 0,
    "availabilities": [
      "Hebra Mountains",
      "Akkala Highlands"
    ],
    "description": "More blades means more attack power! It can be used as a boomerang, but all those blades make that a bit more dangerous. Carried by Black Lizalfos seasoned in battle."
  },
  {
    "id": 33,
    "name": "Guardian Sword",
    "cssClassName": "guardian-sword",
    "attackPowerBase": 20,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 9,
    "durabilityBase": 17,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by Guardian Scout II"
    ],
    "description": "A sword often wielded by Guardian Scouts. Its blue energy blade is a product of ancient technology. It's not very durable."
  },
  {
    "id": 34,
    "name": "Guardian Sword+",
    "cssClassName": "guardian-sword-plus",
    "attackPowerBase": 30,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 9,
    "durabilityBase": 26,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 13,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by Guardian Scout III"
    ],
    "description": "This Guardian sword has enhanced power over the standard model. Its cutting capabilities are improved, and its durability has seen a slight uptick."
  },
  {
    "id": 35,
    "name": "Guardian Sword++",
    "cssClassName": "guardian-sword-plus-plus",
    "attackPowerBase": 40,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 10,
    "attackPowerBonus2Min": 11,
    "attackPowerBonus2Max": 20,
    "durabilityBase": 32,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by Guardian Scout IV"
    ],
    "description": "The abilities of this Guardian sword have been boosted to the maximum, as evidenced by its increase in size. It slices through armor like a hot knife through butter!"
  },
  {
    "id": 36,
    "name": "Lynel Sword",
    "cssClassName": "lynel-sword",
    "attackPowerBase": 24,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 11,
    "durabilityBase": 17,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by Lynels"
    ],
    "description": "This Lynel-made sword was designed with smashing in mind rather than slicing. It's on the heavy side compared to what Hylians are used to, but it's very strong."
  },
  {
    "id": 37,
    "name": "Mighty Lynel Sword",
    "cssClassName": "mighty-lynel-sword",
    "attackPowerBase": 36,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 11,
    "attackPowerBonus2Min": 12,
    "attackPowerBonus2Max": 21,
    "durabilityBase": 32,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by Blue-Maned Lynels"
    ],
    "description": "This Lynel-made sword boasts more blades and more attack power. A skilled Lynel can draw this sword simply in passing and still cut a foe in two."
  },
  {
    "id": 38,
    "name": "Savage Lynel Sword",
    "cssClassName": "savage-lynel-sword",
    "attackPowerBase": 58,
    "attackPowerBonusMin": 11,
    "attackPowerBonusMax": 21,
    "attackPowerBonus2Min": 22,
    "attackPowerBonus2Max": 42,
    "durabilityBase": 41,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 21,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by White-Maned Lynels",
      "Silver Lynels"
    ],
    "description": "A brutal sword carried by white-haired Lynels. The savage blades are strong enough to cut down any foe, no matter how strong."
  },
  {
    "id": 39,
    "name": "Fire Rod",
    "cssClassName": "fire-rod",
    "attackPowerBase": 5,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 8,
    "durabilityBase": 14,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "1 fire ball",
    "throwDistanceBase": 30,
    "throwDistanceMin": 0,
    "throwDistanceMax": 0,
    "availabilities": [
      "Gerudo Highlands",
      "Great Hyrule Forest"
    ],
    "description": "A magical rod that can cast fireballs. The rod will break if it strikes something directly, so use it wisely."
  },
  {
    "id": 40,
    "name": "Meteor Rod",
    "cssClassName": "meteor-rod",
    "attackPowerBase": 10,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 16,
    "durabilityBase": 32,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "3 fire balls",
    "throwDistanceBase": 30,
    "throwDistanceMin": 0,
    "throwDistanceMax": 0,
    "availabilities": [
      "Crenel Hills",
      "Hebra Mountains"
    ],
    "description": "A magical rod that can cast three fireballs at once, crafted by an ancient magician. It will break upon running out of magical energy, so make it last!"
  },
  {
    "id": 41,
    "name": "Ice Rod",
    "cssClassName": "ice-rod",
    "attackPowerBase": 5,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 8,
    "durabilityBase": 14,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "1 ice ball",
    "throwDistanceBase": 30,
    "throwDistanceMin": 0,
    "throwDistanceMax": 0,
    "availabilities": [
      "Gerudo Highlands",
      "Eldin Canyon"
    ],
    "description": "A magical rod crafted from refined ice found in the Hebra Mountains. This rod can cast waves of freezing air. Great for magic—not so great for melee."
  },
  {
    "id": 42,
    "name": "Blizzard Rod",
    "cssClassName": "blizzard-rod",
    "attackPowerBase": 10,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 16,
    "durabilityBase": 32,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "3 ice balls",
    "throwDistanceBase": 30,
    "throwDistanceMin": 0,
    "throwDistanceMax": 0,
    "availabilities": [
      "Gerudo Highlands",
      "Hebra Mountains",
      "Crenel Hills"
    ],
    "description": "A magical rod that can cast extreme cold in a wide range. These are crafted from refined ice found at the summit of Hebra Peak. It will break when depleted."
  },
  {
    "id": 43,
    "name": "Lightning Rod",
    "cssClassName": "lightning-rod",
    "attackPowerBase": 5,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 8,
    "durabilityBase": 14,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "1 electric ball",
    "throwDistanceBase": 30,
    "throwDistanceMin": 0,
    "throwDistanceMax": 0,
    "availabilities": [
      "West Necluda",
      "Hyrule Ridge"
    ],
    "description": "A magical rod that can shoot balls of electricity. Its gem contains lightning from the Hyrule Hills. It's not recommended to use as a melee weapon."
  },
  {
    "id": 44,
    "name": "Thunderstorm Rod",
    "cssClassName": "thunderstorm-rod",
    "attackPowerBase": 10,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 16,
    "durabilityBase": 32,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "3 electric balls",
    "throwDistanceBase": 30,
    "throwDistanceMin": 0,
    "throwDistanceMax": 0,
    "availabilities": [
      "Crenel Hills",
      "Hyrule Ridge"
    ],
    "description": "A magical rod that can hurl three balls of electricity at once. Its gem contains electricity from the Hyrule Hills, and the rod will break when that electricity runs out."
  },
  {
    "id": 45,
    "name": "Vicious Sickle",
    "cssClassName": "vicious-sickle",
    "attackPowerBase": 16,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 13,
    "durabilityBase": 14,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 6,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by Yiga Footsoldiers"
    ],
    "description": "A grim weapon favored by the Yiga. The half-moon shape of the blade allows for the rapid delivery of fatal wounds and serves as a symbol of their terror. Its durability is low."
  },
  {
    "id": 46,
    "name": "Demon Carver",
    "cssClassName": "demon-carver",
    "attackPowerBase": 40,
    "attackPowerBonusMin": 7,
    "attackPowerBonusMax": 14,
    "attackPowerBonus2Min": 15,
    "attackPowerBonus2Max": 27,
    "durabilityBase": 25,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 12,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by Yiga Footsoldiers"
    ],
    "description": "This lethal weapon is forged by the Yiga. Its unique shape facilitates the sound dispatching of any target and strikes fear into the hearts of all who see it."
  },
  {
    "id": 47,
    "name": "Bokoblin Arm",
    "cssClassName": "bokoblin-arm",
    "attackPowerBase": 5,
    "attackPowerBonusMin": 1,
    "attackPowerBonusMax": 2,
    "attackPowerBonus2Min": 3,
    "attackPowerBonus2Max": 5,
    "durabilityBase": 5,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 5,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by Stalkoblins"
    ],
    "description": "A skeletal arm that keeps moving even after it's severed from its body. It's kind of gross to strap it to your back, but it'll do in a pinch. It's old and fragile, so it's quick to break."
  },
  {
    "id": 48,
    "name": "Lizalfos Arm",
    "cssClassName": "lizalfos-arm",
    "attackPowerBase": 12,
    "attackPowerBonusMin": 1,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 8,
    "durabilityBase": 8,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 8,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 0,
    "throwDistanceMax": 0,
    "availabilities": [
      "Dropped by Stalizalfos"
    ],
    "description": "The arm of a Stalizalfos that continues to struggle even in death. It can be used as a weapon, but it's very brittle. You can feel it wiggling when you strap it to your back..."
  },
  {
    "id": 49,
    "name": "Korok Leaf",
    "cssClassName": "korok-leaf",
    "attackPowerBase": 1,
    "attackPowerBonusMin": 0,
    "attackPowerBonusMax": 0,
    "attackPowerBonus2Min": 0,
    "attackPowerBonus2Max": 0,
    "durabilityBase": 25,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 12,
    "throwDistanceEffect": "Wind gust",
    "throwDistanceBase": 5,
    "throwDistanceMin": 0,
    "throwDistanceMax": 0,
    "availabilities": [
      "Hyrule Field",
      "West Necluda"
    ],
    "description": "A single swing of this giant, sturdy leaf can create a gust of wind strong enough to blow away light objects."
  },
  {
    "id": 50,
    "name": "Farming Hoe",
    "cssClassName": "farming-hoe",
    "attackPowerBase": 16,
    "attackPowerBonusMin": 8,
    "attackPowerBonusMax": 14,
    "attackPowerBonus2Min": 15,
    "attackPowerBonus2Max": 20,
    "durabilityBase": 6,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 3,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Field",
      "West Necluda"
    ],
    "description": "A farming tool primarily used for tilling fields. Its fine craftsmanship is sturdy enough to withstand backbreaking fieldwork, but its battle applications are untested."
  },
  {
    "id": 51,
    "name": "Boat Oar",
    "cssClassName": "boat-oar",
    "attackPowerBase": 14,
    "attackPowerBonusMin": 7,
    "attackPowerBonusMax": 13,
    "attackPowerBonus2Min": 14,
    "attackPowerBonus2Max": 26,
    "durabilityBase": 8,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 4,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "East Necluda",
      "Necluda Sea"
    ],
    "description": "Made for paddling boats, but it was made sturdy enough to fight strong currents. Maybe it's useful for self-defense in a pinch."
  },
  {
    "id": 52,
    "name": "Woodcutter's Axe",
    "cssClassName": "woodcutters-axe",
    "attackPowerBase": 3,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 6,
    "durabilityBase": 47,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "At various stables"
    ],
    "description": "A woodcutter's tool of choice for felling trees. Its formidable weight and uneven balancing make it a slow, inefficient weapon."
  },
  {
    "id": 53,
    "name": "Double Axe",
    "cssClassName": "double-axe",
    "attackPowerBase": 18,
    "attackPowerBonusMin": 9,
    "attackPowerBonusMax": 16,
    "attackPowerBonus2Min": 17,
    "attackPowerBonus2Max": 22,
    "durabilityBase": 52,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 21,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "At various stables"
    ],
    "description": "This double-sided axe was designed with fighting in mind. It's a bit unwieldy, so it requires a well-practiced technique to use efficiently."
  },
  {
    "id": 54,
    "name": "Iron Sledgehammer",
    "cssClassName": "iron-sledgehammer",
    "attackPowerBase": 12,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 11,
    "attackPowerBonus2Min": 12,
    "attackPowerBonus2Max": 22,
    "durabilityBase": 40,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Eldin Canyon",
      "Akkala Highlands",
      "Tanagar Canyon Course"
    ],
    "description": "This large iron sledgehammer was originally used for mining, but it works reasonably well as a weapon too."
  },
  {
    "id": 55,
    "name": "Giant Boomerang",
    "cssClassName": "giant-boomerang",
    "attackPowerBase": 25,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 11,
    "attackPowerBonus2Min": 12,
    "attackPowerBonus2Max": 22,
    "durabilityBase": 40,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 0,
    "throwDistanceMax": 0,
    "availabilities": [
      "West Necluda",
      "Hebra Mountains"
    ],
    "description": "This massive boomerang requires two hands. Originally used for hunting, it was modified for use as a weapon. The blades on the inner curves make it a bit tricky to wield."
  },
  {
    "id": 56,
    "name": "Traveler's Claymore",
    "cssClassName": "travelers-claymore",
    "attackPowerBase": 10,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 9,
    "durabilityBase": 20,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 4,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Field",
      "West Necluda"
    ],
    "description": "A basic two-handed sword often wielded by aspiring adventurers. Its immense weight can knock enemies' shields right out of their hands."
  },
  {
    "id": 57,
    "name": "Soldier's Claymore",
    "cssClassName": "soldiers-claymore",
    "attackPowerBase": 20,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 9,
    "attackPowerBonus2Min": 10,
    "attackPowerBonus2Max": 17,
    "durabilityBase": 25,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 3,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Field",
      "Faron Grasslands"
    ],
    "description": "A two-handed sword designed for combat. It's heavy and hard to use but has decent build quality and durability."
  },
  {
    "id": 58,
    "name": "Knight's Claymore",
    "cssClassName": "knights-claymore",
    "attackPowerBase": 38,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 7,
    "attackPowerBonus2Min": 8,
    "attackPowerBonus2Max": 13,
    "durabilityBase": 30,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 8,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Gerudo Desert",
      "Tabantha Frontier"
    ],
    "description": "Only the most confident of Hyrule Castle's knights carried this two-handed sword. Its cutting edge is finely honed."
  },
  {
    "id": 59,
    "name": "Royal Claymore",
    "cssClassName": "royal-claymore",
    "attackPowerBase": 52,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 10,
    "attackPowerBonus2Min": 11,
    "attackPowerBonus2Max": 20,
    "durabilityBase": 40,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Gerudo Desert",
      "Tabantha Frontier",
      "Hyrule Castle"
    ],
    "description": "A two-handed sword issued to the Hyrulean royal family's immediate guard detail. Its powerful strikes are said to crush an opponent's body and resolve alike."
  },
  {
    "id": 60,
    "name": "Silver Longsword",
    "cssClassName": "silver-longsword",
    "attackPowerBase": 22,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 19,
    "durabilityBase": 30,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 14,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Lanayru Great Spring",
      "Lanayru Wetlands"
    ],
    "description": "Although the Zora prefer spears to swords, they made this two-handed weapon using a special metal. It found popularity among Hylians for its unique design."
  },
  {
    "id": 61,
    "name": "Cobble Crusher",
    "cssClassName": "cobble-crusher",
    "attackPowerBase": 15,
    "attackPowerBonusMin": 7,
    "attackPowerBonusMax": 14,
    "attackPowerBonus2Min": 15,
    "attackPowerBonus2Max": 26,
    "durabilityBase": 30,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 14,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Eldin Canyon",
      "Eldin Mountains"
    ],
    "description": "A Goron-made two-handed weapon. It's made from thick, hard metal and has no cutting edge, so it relies on its sheer weight to crush all opponents."
  },
  {
    "id": 62,
    "name": "Stone Smasher",
    "cssClassName": "stone-smasher",
    "attackPowerBase": 42,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 9,
    "attackPowerBonus2Min": 10,
    "attackPowerBonus2Max": 17,
    "durabilityBase": 40,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Eldin Canyon",
      "Hyrule Field"
    ],
    "description": "A two-handed weapon forged from a rare metal mined in Goron City. Its center of gravity is at its tip, so it uses centrifugal force and its sheer weight to smash opponents flat."
  },
  {
    "id": 63,
    "name": "Boulder Breaker",
    "cssClassName": "boulder-breaker",
    "attackPowerBase": 60,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 15,
    "durabilityBase": 60,
    "durabilityBonusMin": 6,
    "durabilityBonusMax": 11,
    "durabilityBonus2Min": 12,
    "durabilityBonus2Max": 27,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Reward for clearing Divine Beast Vah Rudania dungeon"
    ],
    "description": "This two-handed weapon was once wielded by the Goron Champion Daruk. Daruk made swinging it around look easy, but a Hylian would need an immense amount of strength."
  },
  {
    "id": 64,
    "name": "Golden Claymore",
    "cssClassName": "golden-claymore",
    "attackPowerBase": 28,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 15,
    "durabilityBase": 30,
    "durabilityBonusMin": 6,
    "durabilityBonusMax": 11,
    "durabilityBonus2Min": 12,
    "durabilityBonus2Max": 27,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Gerudo Highlands",
      "Hyrule Ridge"
    ],
    "description": "Only the most talented Gerudo sword fighters carry this two-handed sword. It's actually much lighter than it appears and is surprisingly easy to wield."
  },
  {
    "id": 65,
    "name": "Eightfold Longblade",
    "cssClassName": "eightfold-longblade",
    "attackPowerBase": 32,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 11,
    "durabilityBase": 25,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 12,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "West Necluda",
      "Lanayru Great Spring"
    ],
    "description": "A single-edged sword seldom seen in Hyrule. This weapon is passed down through the Sheikah tribe and has an astonishingly sharp edge ideal for slicing."
  },
  {
    "id": 66,
    "name": "Edge of Duality",
    "cssClassName": "edge-of-duality",
    "attackPowerBase": 50,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 10,
    "attackPowerBonus2Min": 11,
    "attackPowerBonus2Max": 19,
    "durabilityBase": 35,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Field",
      "West Necluda"
    ],
    "description": "A curious double-edged sword crafted using Sheikah technology. It was originally made for Hyrulean knights unfamiliar with single-edged blades."
  },
  {
    "id": 67,
    "name": "Ancient Bladesaw",
    "cssClassName": "ancient-bladesaw",
    "attackPowerBase": 55,
    "attackPowerBonusMin": 11,
    "attackPowerBonusMax": 20,
    "attackPowerBonus2Min": 21,
    "attackPowerBonus2Max": 33,
    "durabilityBase": 50,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 23,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Akkala Ancient Tech Lab"
    ],
    "description": "This two-handed sword was forged using ancient Sheikah technology. Its unique rotating blades give it impressive cutting power that will slice enemies to shreds."
  },
  {
    "id": 68,
    "name": "Rusty Claymore",
    "cssClassName": "rusty-claymore",
    "attackPowerBase": 12,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 11,
    "attackPowerBonus2Min": 12,
    "attackPowerBonus2Max": 22,
    "durabilityBase": 10,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 5,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Field",
      "Eldin Canyon",
      "Hyrule Castle"
    ],
    "description": "A two-handed sword not properly cared for. Although it can be used as a weapon, its durability is very low. Don't expect it to last for more than a few strikes."
  },
  {
    "id": 69,
    "name": "Royal Guard's Claymore",
    "cssClassName": "royal-guards-claymore",
    "attackPowerBase": 72,
    "attackPowerBonusMin": 14,
    "attackPowerBonusMax": 26,
    "attackPowerBonus2Min": 27,
    "attackPowerBonus2Max": 44,
    "durabilityBase": 15,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 35,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Castle"
    ],
    "description": "The Sheikah used the very essence of ancient technology to forge this greatsword. It was designed to oppose the Calamity, but its low durability made it impractical in battle."
  },
  {
    "id": 70,
    "name": "Great Flameblade",
    "cssClassName": "great-flameblade",
    "attackPowerBase": 34,
    "attackPowerBonusMin": 7,
    "attackPowerBonusMax": 12,
    "attackPowerBonus2Min": 13,
    "attackPowerBonus2Max": 21,
    "durabilityBase": 50,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 15,
    "durabilityBonus2Min": 16,
    "durabilityBonus2Max": 30,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Coliseum Ruins",
      "Eldin Canyon"
    ],
    "description": "This magic-infused greatsword was forged in the fires of Death Mountain by Goron smiths in an ancient age. Attack when the blade glows red to expel flames."
  },
  {
    "id": 71,
    "name": "Great Frostblade",
    "cssClassName": "great-frostblade",
    "attackPowerBase": 30,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 11,
    "attackPowerBonus2Min": 12,
    "attackPowerBonus2Max": 18,
    "durabilityBase": 40,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 15,
    "durabilityBonus2Min": 16,
    "durabilityBonus2Max": 30,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Coliseum Ruins",
      "Hebra Mountains"
    ],
    "description": "This magic-infused greatsword was forged by smelting ore found in the Hebra Mountains' permafrost. Attack when the blade glows blue to expel freezing air."
  },
  {
    "id": 72,
    "name": "Great Thunderblade",
    "cssClassName": "great-thunderblade",
    "attackPowerBase": 32,
    "attackPowerBonusMin": 7,
    "attackPowerBonusMax": 12,
    "attackPowerBonus2Min": 13,
    "attackPowerBonus2Max": 20,
    "durabilityBase": 50,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 15,
    "durabilityBonus2Min": 16,
    "durabilityBonus2Max": 30,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Coliseum Ruins",
      "Tabantha Frontier"
    ],
    "description": "This magic-infused greatsword was forged by the Hyrulean royal family using lightning from the Hyrule Hills. Attack when the blade glows golden to expel lightning."
  },
  {
    "id": 73,
    "name": "Sword of the Six Sages",
    "cssClassName": "sword-of-the-six-sages",
    "attackPowerBase": 48,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 10,
    "attackPowerBonus2Min": 11,
    "attackPowerBonus2Max": 19,
    "durabilityBase": 50,
    "durabilityBonusMin": 8,
    "durabilityBonusMax": 25,
    "durabilityBonus2Min": 26,
    "durabilityBonus2Max": 43,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Unlocked by corresponding amiibo"
    ],
    "description": "The Six Sages are said to have forged this longsword to seal a demon king in the world where the hero fought against the beasts of twilight. The blade shines with a holy luster."
  },
  {
    "id": 74,
    "name": "Biggoron's Sword",
    "cssClassName": "biggorons-sword",
    "attackPowerBase": 50,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 10,
    "attackPowerBonus2Min": 11,
    "attackPowerBonus2Max": 19,
    "durabilityBase": 60,
    "durabilityBonusMin": 9,
    "durabilityBonusMax": 30,
    "durabilityBonus2Min": 31,
    "durabilityBonus2Max": 51,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Unlocked by corresponding amiibo"
    ],
    "description": "A legendary greatsword forged by a Goron craftsman for a hero who traveled through time. The exceptionally sharp cutting edge is a testament to the craftsman's mastery."
  },
  {
    "id": 75,
    "name": "Fierce Deity Sword",
    "cssClassName": "fierce-deity-sword",
    "attackPowerBase": 60,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 12,
    "attackPowerBonus2Min": 13,
    "attackPowerBonus2Max": 23,
    "durabilityBase": 35,
    "durabilityBonusMin": 6,
    "durabilityBonusMax": 18,
    "durabilityBonus2Min": 19,
    "durabilityBonus2Max": 30,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Unlocked by corresponding amiibo"
    ],
    "description": "A peculiar greatsword allegedly used by a hero from a world in which the moon threatened to fall. It slashes wildly in battle as if possessed by a fierce deity."
  },
  {
    "id": 76,
    "name": "Boko Bat",
    "cssClassName": "boko-bat",
    "attackPowerBase": 6,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 11,
    "durabilityBase": 8,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 4,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Field",
      "West Necluda"
    ],
    "description": "A clunky club made by a Bokoblin. If you swing it at an enemy's shield, it may be able to knock the shield out of your foe's hand."
  },
  {
    "id": 77,
    "name": "Spiked Boko Bat",
    "cssClassName": "spiked-boko-bat",
    "attackPowerBase": 18,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 9,
    "attackPowerBonus2Min": 10,
    "attackPowerBonus2Max": 17,
    "durabilityBase": 12,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 6,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Faron Grasslands",
      "East Necluda"
    ],
    "description": "After much consideration by Bokoblins on how to improve the Boko bat, they simply attached sharp spikes to it. A skilled fighter can cause immense damage with this."
  },
  {
    "id": 78,
    "name": "Dragonbone Boko Bat",
    "cssClassName": "dragonbone-boko-bat",
    "attackPowerBase": 36,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 12,
    "attackPowerBonus2Min": 13,
    "attackPowerBonus2Max": 24,
    "durabilityBase": 16,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 8,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Ridge",
      "Necluda Sea"
    ],
    "description": "Used by only the toughest Bokoblin warriors, this Boko bat has been fortified by fossilized bone. It boasts a high durability and is strong enough to beat down powerful foes."
  },
  {
    "id": 79,
    "name": "Moblin Club",
    "cssClassName": "moblin-club",
    "attackPowerBase": 9,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 9,
    "attackPowerBonus2Min": 10,
    "attackPowerBonus2Max": 17,
    "durabilityBase": 12,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 6,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Field",
      "West Necluda"
    ],
    "description": "A crudely fashioned club favored by Moblins. It's carved from a sturdy tree but is sloppily made, so it breaks easily."
  },
  {
    "id": 80,
    "name": "Spiked Moblin Club",
    "cssClassName": "spiked-moblin-club",
    "attackPowerBase": 27,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 9,
    "attackPowerBonus2Min": 10,
    "attackPowerBonus2Max": 17,
    "durabilityBase": 18,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Field",
      "Akkala Highlands"
    ],
    "description": "Animal bone has been affixed to this Moblin club to greatly improve its damage."
  },
  {
    "id": 81,
    "name": "Dragonbone Moblin Club",
    "cssClassName": "dragonbone-moblin-club",
    "attackPowerBase": 36,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 12,
    "attackPowerBonus2Min": 13,
    "attackPowerBonus2Max": 24,
    "durabilityBase": 16,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 8,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Ridge",
      "Necluda Sea"
    ],
    "description": "The bone of an ancient beast has been affixed to this Moblin club, further increasing its damage. Moblins carrying these in battle are particularly dangerous."
  },
  {
    "id": 82,
    "name": "Ancient Battle Axe",
    "cssClassName": "ancient-battle-axe",
    "attackPowerBase": 30,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 14,
    "durabilityBase": 15,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by Guardian Scout II"
    ],
    "description": "A weapon used by Guardian Scouts. Its unique blade was forged using ancient technology. Although powerful, its unusual shape causes it to break easily."
  },
  {
    "id": 83,
    "name": "Ancient Battle Axe+",
    "cssClassName": "ancient-battle-axe-plus",
    "attackPowerBase": 45,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 14,
    "durabilityBase": 20,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by Guardian Scout III"
    ],
    "description": "This ancient battle axe's damage output has been increased to maximum. It's sharp enough to cut through almost anything, so it may have been used to forge new routes."
  },
  {
    "id": 84,
    "name": "Ancient Battle Axe++",
    "cssClassName": "ancient-battle-axe-plus-plus",
    "attackPowerBase": 60,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 15,
    "durabilityBase": 25,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 12,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by Guardian Scout IV"
    ],
    "description": "This ancient battle axe's damage output is scaled up to peak performance. Ancient technology makes it possible to enhance cutting power beyond metal weapons' limits."
  },
  {
    "id": 85,
    "name": "Lynel Crusher",
    "cssClassName": "lynel-crusher",
    "attackPowerBase": 36,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 9,
    "attackPowerBonus2Min": 10,
    "attackPowerBonus2Max": 17,
    "durabilityBase": 20,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by Lynels"
    ],
    "description": "This two-handed weapon is favored by the Lynels. It may be more accurate to call it a lump of metal than a weapon, but if wielded by a Lynel, it can pound you into a fine dust."
  },
  {
    "id": 86,
    "name": "Mighty Lynel Crusher",
    "cssClassName": "mighty-lynel-crusher",
    "attackPowerBase": 54,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 12,
    "attackPowerBonus2Min": 13,
    "attackPowerBonus2Max": 23,
    "durabilityBase": 25,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 12,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by Blue-Maned Lynels"
    ],
    "description": "This Lynel-made two-handed weapon has been reinforced to increase its durability and striking power. Its overwhelming heft will crush your foe, shield and all."
  },
  {
    "id": 87,
    "name": "Savage Lynel Crusher",
    "cssClassName": "savage-lynel-crusher",
    "attackPowerBase": 78,
    "attackPowerBonusMin": 8,
    "attackPowerBonusMax": 15,
    "attackPowerBonus2Min": 16,
    "attackPowerBonus2Max": 30,
    "durabilityBase": 35,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by White-Maned Lynels",
      "Silver Lynels"
    ],
    "description": "This Lynel-made two-handed weapon is immensely heavy thanks to a rare metal from Death Mountain's peak. The power of its downward swing is in a class all its own."
  },
  {
    "id": 88,
    "name": "Windcleaver",
    "cssClassName": "windcleaver",
    "attackPowerBase": 40,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 14,
    "durabilityBase": 25,
    "durabilityBonusMin": 6,
    "durabilityBonusMax": 15,
    "durabilityBonus2Min": 16,
    "durabilityBonus2Max": 24,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 20,
    "throwDistanceMin": 1,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by Yiga Blademasters"
    ],
    "description": "This sword is favored by high-ranking members of the Yiga. When wielded by a proficient fighter, its unique shape cleaves the very wind and creates a vacuum."
  },
  {
    "id": 89,
    "name": "Moblin Arm",
    "cssClassName": "moblin-arm",
    "attackPowerBase": 15,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 13,
    "durabilityBase": 5,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 20,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by Stalmoblins"
    ],
    "description": "A Moblin bone that continues to move even after being detached from its body. The bone is thick enough to be used as a weapon but is extremely brittle and easily broken."
  },
  {
    "id": 90,
    "name": "Wooden Mop",
    "cssClassName": "wooden-mop",
    "attackPowerBase": 5,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 5,
    "durabilityBase": 8,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 4,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "East Necluda",
      "Hyrule Field"
    ],
    "description": "Just a mop to the untrained eye, it excels at tidying up the place. But it owes its sturdy construction to a true craftsman, so it actually has some combat merit."
  },
  {
    "id": 91,
    "name": "Farmer's Pitchfork",
    "cssClassName": "farmers-pitchfork",
    "attackPowerBase": 7,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 6,
    "durabilityBase": 12,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 6,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "East Necluda",
      "West Necluda"
    ],
    "description": "A farming tool used to collect hay efficiently. It's light enough to be used by anyone. The four prongs are very sharp."
  },
  {
    "id": 92,
    "name": "Fishing Harpoon",
    "cssClassName": "fishing-harpoon",
    "attackPowerBase": 8,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 6,
    "durabilityBase": 12,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 6,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "East Necluda",
      "Lake Hylia"
    ],
    "description": "A fisherman's tool that excels at catching large fish. Its particularly sharp spearhead makes it valuable as a weapon as well."
  },
  {
    "id": 93,
    "name": "Throwing Spear",
    "cssClassName": "throwing-spear",
    "attackPowerBase": 6,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 12,
    "durabilityBase": 20,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "West Necluda",
      "Hyrule Field"
    ],
    "description": "A specialized spear weighted to excel as a throwing weapon. It's perfectly balanced to be thrown farther than your average spear, able to pierce targets from a great distance."
  },
  {
    "id": 94,
    "name": "Traveler's Spear",
    "cssClassName": "travelers-spear",
    "attackPowerBase": 3,
    "attackPowerBonusMin": 1,
    "attackPowerBonusMax": 2,
    "attackPowerBonus2Min": 3,
    "attackPowerBonus2Max": 3,
    "durabilityBase": 30,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 4,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "West Necluda",
      "Hyrule Field"
    ],
    "description": "A spear used mainly by travelers to fend off wolves and other beasts. It's easy to hold and simple to use."
  },
  {
    "id": 95,
    "name": "Soldier's Spear",
    "cssClassName": "soldiers-spear",
    "attackPowerBase": 7,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 5,
    "durabilityBase": 35,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 3,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Field",
      "Faron Grasslands"
    ],
    "description": "A long spear once used by the guards of Hyrule Castle. Easy to use but difficult to master. The iron tip is very sturdy and the shaft will not burn when exposed to flame."
  },
  {
    "id": 96,
    "name": "Knight's Halberd",
    "cssClassName": "knights-halberd",
    "attackPowerBase": 13,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 7,
    "attackPowerBonus2Min": 8,
    "attackPowerBonus2Max": 12,
    "durabilityBase": 40,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 8,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Tabantha Frontier",
      "Gerudo Desert"
    ],
    "description": "A spear used by knights adept in mounted combat. The spearhead is modeled after an axe."
  },
  {
    "id": 97,
    "name": "Royal Halberd",
    "cssClassName": "royal-halberd",
    "attackPowerBase": 26,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 10,
    "attackPowerBonus2Min": 11,
    "attackPowerBonus2Max": 20,
    "durabilityBase": 50,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 15,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Gerudo Highlands",
      "Tabantha Frontier"
    ],
    "description": "This spear was issued to the knights who guarded Hyrule Castle's throne room. Its ornate design was applied by a craftsman in service to the royal family."
  },
  {
    "id": 98,
    "name": "Forest Dweller's Spear",
    "cssClassName": "forest-dwellers-spear",
    "attackPowerBase": 11,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 11,
    "durabilityBase": 35,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Great Hyrule Forest",
      "Hyrule Ridge"
    ],
    "description": "The Koroks made this spear for Hylians. The shaft is made from a light, sturdy wood, offering ease of use. The spearhead is made from a much harder wood, offering strength."
  },
  {
    "id": 99,
    "name": "Zora Spear",
    "cssClassName": "zora-spear",
    "attackPowerBase": 9,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 7,
    "durabilityBase": 40,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Lanayru Great Spring",
      "Lake Hylia"
    ],
    "description": "This spear is a Zora's weapon of choice. It's lighter than it looks due to being made from a special metal and is used by the Zora for both fishing and protecting their domain."
  },
  {
    "id": 100,
    "name": "Silverscale Spear",
    "cssClassName": "silverscale-spear",
    "attackPowerBase": 12,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 7,
    "attackPowerBonus2Min": 8,
    "attackPowerBonus2Max": 12,
    "durabilityBase": 40,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Akkala Highlands",
      "Lanayru Great Spring"
    ],
    "description": "The most skilled Zora fighters wield this spear. Its beautiful fish-tail design belies its impressive strength; the spearhead can pierce even the toughest scales."
  },
  {
    "id": 101,
    "name": "Ceremonial Trident",
    "cssClassName": "ceremonial-trident",
    "attackPowerBase": 14,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 13,
    "durabilityBase": 40,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 14,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Zora's Domain"
    ],
    "description": "A spear modeled after the Lightscale Trident wielded by the Zora Champion Mipha. They may be identical in appearance, but this spear's strength and durability are inferior."
  },
  {
    "id": 102,
    "name": "Lightscale Trident",
    "cssClassName": "lightscale-trident",
    "attackPowerBase": 22,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 9,
    "attackPowerBonus2Min": 10,
    "attackPowerBonus2Max": 18,
    "durabilityBase": 70,
    "durabilityBonusMin": 7,
    "durabilityBonusMax": 13,
    "durabilityBonus2Min": 14,
    "durabilityBonus2Max": 32,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Reward for clearing Divine Beast Vah Ruta dungeon"
    ],
    "description": "A spear of peerless grace cherished by the Zora Champion Mipha. Although Mipha specialized in healing abilities, her spearmanship was in a class all its own."
  },
  {
    "id": 103,
    "name": "Drillshaft",
    "cssClassName": "drillshaft",
    "attackPowerBase": 14,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 13,
    "durabilityBase": 50,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 23,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Eldin Canyon",
      "Hebra Mountains"
    ],
    "description": "Goron artisans used recycled metal to forge this weapon. The tip is made from an old excavation bore, which affords it unmatched piercing capabilities."
  },
  {
    "id": 104,
    "name": "Feathered Spear",
    "cssClassName": "feathered-spear",
    "attackPowerBase": 10,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 8,
    "durabilityBase": 35,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Tabantha Frontier",
      "Hyrule Field"
    ],
    "description": "Its lightweight design is a hallmark of Rito craftsmanship. It's made from light and sturdy materials, which afford Rito warriors ease of use during aerial combat."
  },
  {
    "id": 105,
    "name": "Gerudo Spear",
    "cssClassName": "gerudo-spear",
    "attackPowerBase": 16,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 9,
    "attackPowerBonus2Min": 10,
    "attackPowerBonus2Max": 15,
    "durabilityBase": 35,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Gerudo Highlands",
      "Gerudo Desert"
    ],
    "description": "This spear's center of gravity is in its tip, making it a bit unwieldy for the average fighter. But in the hands of a skilled Gerudo warrior, it's a weapon of reliable strength."
  },
  {
    "id": 106,
    "name": "Serpentine Spear",
    "cssClassName": "serpentine-spear",
    "attackPowerBase": 12,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 7,
    "attackPowerBonus2Min": 8,
    "attackPowerBonus2Max": 12,
    "durabilityBase": 35,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "East Necluda",
      "Hyrule Field"
    ],
    "description": "The spearhead of this weapon is uniquely Sheikah in design. Spear masters of the Sheikah tribe can use the crescent shape to snag their opponents and deliver brutal cuts."
  },
  {
    "id": 107,
    "name": "Ancient Spear",
    "cssClassName": "ancient-spear",
    "attackPowerBase": 30,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 12,
    "attackPowerBonus2Min": 13,
    "attackPowerBonus2Max": 24,
    "durabilityBase": 50,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 23,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Akkala Ancient Tech Lab"
    ],
    "description": "This spear is the result of countless hours of research into the ancient technology used by Guardians. The glowing spearhead has high piercing potential."
  },
  {
    "id": 108,
    "name": "Rusty Halberd",
    "cssClassName": "rusty-halberd",
    "attackPowerBase": 5,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 10,
    "durabilityBase": 15,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Field",
      "Great Hyrule Forest"
    ],
    "description": "A rusty polearm likely used by knights from an age past. The spearhead is in bad shape due to prolonged exposure to the elements, so its durability is low."
  },
  {
    "id": 109,
    "name": "Royal Guard's Spear",
    "cssClassName": "royal-guards-spear",
    "attackPowerBase": 32,
    "attackPowerBonusMin": 7,
    "attackPowerBonusMax": 13,
    "attackPowerBonus2Min": 14,
    "attackPowerBonus2Max": 25,
    "durabilityBase": 15,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hyrule Castle"
    ],
    "description": "This Sheikah-made spear was created using ancient technology to combat the Calamity. Its attack power is very high, but a critical design flaw left it with poor durability."
  },
  {
    "id": 110,
    "name": "Flamespear",
    "cssClassName": "flamespear",
    "attackPowerBase": 24,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 10,
    "attackPowerBonus2Min": 11,
    "attackPowerBonus2Max": 19,
    "durabilityBase": 50,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 23,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Coliseum Ruins",
      "Hebra Mountains"
    ],
    "description": "A magical spear forged in the magma of Death Mountain. Attack when the blade glows to expel powerful flames."
  },
  {
    "id": 111,
    "name": "Frostspear",
    "cssClassName": "frostspear",
    "attackPowerBase": 20,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 16,
    "durabilityBase": 40,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 23,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Coliseum Ruins",
      "Hebra Mountains"
    ],
    "description": "A magical spear forged from ancient ice taken from the Hebra Mountains. Attack when the blade glows blue to chill the air and freeze your foe."
  },
  {
    "id": 112,
    "name": "Thunderspear",
    "cssClassName": "thunderspear",
    "attackPowerBase": 22,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 9,
    "attackPowerBonus2Min": 10,
    "attackPowerBonus2Max": 18,
    "durabilityBase": 50,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 23,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Coliseum Ruins",
      "Hyrule Ridge"
    ],
    "description": "A magical spear that contains thunder from Thundra Plateau in its tip. Attack when the blade glows with a golden light to unleash an electrical attack."
  },
  {
    "id": 113,
    "name": "Boko Spear",
    "cssClassName": "boko-spear",
    "attackPowerBase": 2,
    "attackPowerBonusMin": 1,
    "attackPowerBonusMax": 2,
    "attackPowerBonus2Min": 3,
    "attackPowerBonus2Max": 3,
    "durabilityBase": 12,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 6,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "West Necluda",
      "Hyrule Field"
    ],
    "description": "A spear recklessly carved from a tree branch. Useful for skewering fish and meat, which can then be cooked over a flame. If it's close to breaking, consider throwing it."
  },
  {
    "id": 114,
    "name": "Spiked Boko Spear",
    "cssClassName": "spiked-boko-spear",
    "attackPowerBase": 6,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 5,
    "durabilityBase": 15,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Faron Grasslands",
      "East Necluda"
    ],
    "description": "A Boko spear enhanced with sharpened animal bones. It's light, easy to use, and deals a decent amount of damage."
  },
  {
    "id": 115,
    "name": "Dragonbone Boko Spear",
    "cssClassName": "dragonbone-boko-spear",
    "attackPowerBase": 12,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 7,
    "durabilityBase": 20,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Necluda Sea",
      "Hyrule Ridge"
    ],
    "description": "This Boko spear has been strengthened with fossilized bones. The bones are positioned outward so the fangs bite at the opponent. Beware Bokoblins carrying this weapon."
  },
  {
    "id": 116,
    "name": "Moblin Spear",
    "cssClassName": "moblin-spear",
    "attackPowerBase": 4,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 4,
    "durabilityBase": 15,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Faron Grasslands",
      "Gerudo Highlands"
    ],
    "description": "This wooden spear is most often used by Moblins. It's made from a hastily whittled tree, so its stabbing power and durability are both pretty low."
  },
  {
    "id": 117,
    "name": "Spiked Moblin Spear",
    "cssClassName": "spiked-moblin-spear",
    "attackPowerBase": 9,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 5,
    "durabilityBase": 20,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Gerudo Highlands",
      "Akkala Highlands"
    ],
    "description": "This Moblin-made spear uses a horned animal bone as the spearhead. Like many Moblin weapons it's sloppily made, but this one packs some respectable piercing power."
  },
  {
    "id": 118,
    "name": "Dragonbone Moblin Spear",
    "cssClassName": "dragonbone-moblin-spear",
    "attackPowerBase": 15,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 7,
    "durabilityBase": 25,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 12,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Hebra Mountains",
      "Eldin Mountains"
    ],
    "description": "This spear is a fan favorite among Moblins. The spearhead is made from fossilized bones adorned with spikes, which greatly increases its stabbing power."
  },
  {
    "id": 119,
    "name": "Lizal Spear",
    "cssClassName": "lizal-spear",
    "attackPowerBase": 7,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 4,
    "durabilityBase": 18,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Lanayru Wetlands",
      "East Necluda"
    ],
    "description": "The brutal, ripping edge of this weapon's spearhead is a distinctly Lizalfos design. Its low durability doesn't lend itself to extended use."
  },
  {
    "id": 120,
    "name": "Enhanced Lizal Spear",
    "cssClassName": "enhanced-lizal-spear",
    "attackPowerBase": 12,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 5,
    "durabilityBase": 22,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 10,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Tabantha Frontier",
      "Gerudo Desert"
    ],
    "description": "Judging by the harpoon-like spearhead of this Lizalfos-made spear, the Lizalfos use it for fishing as well as combat. Try not to get caught on the wrong end of its barbs."
  },
  {
    "id": 121,
    "name": "Forked Lizal Spear",
    "cssClassName": "forked-lizal-spear",
    "attackPowerBase": 18,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 7,
    "durabilityBase": 28,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 13,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Eldin Canyon",
      "Akkala Highlands"
    ],
    "description": "Skilled Lizalfos warriors tend to favor this spear. What it lacks in piercing power, it makes up for with the brutal wounds its dual ripping blades will inflict."
  },
  {
    "id": 122,
    "name": "Guardian Spear",
    "cssClassName": "guardian-spear",
    "attackPowerBase": 10,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 4,
    "durabilityBase": 20,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by Guardian Scout II"
    ],
    "description": "Wielded by Guardian Scouts, this spear has a high piercing power and is a testament to the Sheikah's high level of technology. The spearhead appears only when brandished."
  },
  {
    "id": 123,
    "name": "Guardian Spear+",
    "cssClassName": "guardian-spear-plus",
    "attackPowerBase": 15,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 4,
    "durabilityBase": 25,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 12,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by Guardian Scout III"
    ],
    "description": "The tip of this Guardian spear has been enlarged and strengthened. It's a bit shorter than your average spear, perhaps to facilitate use in tight spaces."
  },
  {
    "id": 124,
    "name": "Guardian Spear++",
    "cssClassName": "guardian-spear-plus-plus",
    "attackPowerBase": 20,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 8,
    "durabilityBase": 35,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by Guardian Scout IV"
    ],
    "description": "This Guardian spear's output has been boosted to the maximum. The spearhead is designed for optimal stabbing, capable of easily piercing most armor."
  },
  {
    "id": 125,
    "name": "Lynel Spear",
    "cssClassName": "lynel-spear",
    "attackPowerBase": 14,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 5,
    "durabilityBase": 25,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 12,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by Lynels"
    ],
    "description": "The crescent-shaped spearhead of this Lynel-made weapon gives it poor balance, making it difficult to wield. Lynels, however, can swing it effectively with a single hand."
  },
  {
    "id": 126,
    "name": "Mighty Lynel Spear",
    "cssClassName": "mighty-lynel-spear",
    "attackPowerBase": 20,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 9,
    "durabilityBase": 35,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by Blue-Maned Lynels"
    ],
    "description": "The weight and cutting edge of this Lynel-made spear have both been enhanced. It's immensely heavy for a Hylian, but a Lynel can cleave through rock with a single swing."
  },
  {
    "id": 127,
    "name": "Savage Lynel Spear",
    "cssClassName": "savage-lynel-spear",
    "attackPowerBase": 30,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 7,
    "attackPowerBonus2Min": 8,
    "attackPowerBonus2Max": 14,
    "durabilityBase": 45,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 21,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2,
    "availabilities": [
      "Dropped by White-Maned Lynels",
      "Silver Lynels"
    ],
    "description": "White-haired Lynels favor this brutal spear. Its axe-like spearhead and exceptional weight give it absolute destructive power."
  }
]
