module.exports = [
  {
    "id": 1,
    "name": "Master Sword",
    "cssClassName": null,
    "attackPowerBase": 30,
    "attackPowerBonusMin": 0,
    "attackPowerBonusMax": 0,
    "attackPowerBonus2Min": 0,
    "attackPowerBonus2Max": 0,
    "durabilityBase": 40,
    "durabilityBonusMin": 0,
    "durabilityBonusMax": 0,
    "durabilityBonus2Min": 0,
    "durabilityBonus2Max": 0,
    "throwDistanceEffect": "Beam (all hearts)",
    "throwDistanceBase": 50,
    "throwDistanceMin": 0.0,
    "throwDistanceMax": 0.0,
    "availabilities": [
      "Korok Forest (main quest: The Hero's Sword)"
    ]
  },
  {
    "id": 2,
    "name": "Tree branch",
    "cssClassName": null,
    "attackPowerBase": 2,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 2,
    "attackPowerBonus2Min": 3,
    "attackPowerBonus2Max": 4,
    "durabilityBase": 4,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 1,
    "durabilityBonus2Min": 2,
    "durabilityBonus2Max": 2,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 4,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Field",
      "West Necluda (cut small trees/shrubs)"
    ]
  },
  {
    "id": 3,
    "name": "Torch",
    "cssClassName": null,
    "attackPowerBase": 2,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 2,
    "attackPowerBonus2Min": 3,
    "attackPowerBonus2Max": 4,
    "durabilityBase": 8,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 4,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 3,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Great Hyrule Forest",
      "Hyrule Field",
      "Inside the Tech Labs"
    ]
  },
  {
    "id": 4,
    "name": "Soup Ladle",
    "cssClassName": null,
    "attackPowerBase": 4,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 7,
    "durabilityBase": 5,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 1,
    "durabilityBonus2Min": 2,
    "durabilityBonus2Max": 45,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Field",
      "Tabantha Frontier (by cooking pots)"
    ]
  },
  {
    "id": 5,
    "name": "Boomerang",
    "cssClassName": null,
    "attackPowerBase": 8,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 15,
    "durabilityBase": 18,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 20,
    "throwDistanceMin": 0.0,
    "throwDistanceMax": 0.0,
    "availabilities": [
      "West Necluda",
      "Faron Grasslands"
    ]
  },
  {
    "id": 6,
    "name": "Spring-Loaded Hammer",
    "cssClassName": null,
    "attackPowerBase": 1,
    "attackPowerBonusMin": 1,
    "attackPowerBonusMax": 1,
    "attackPowerBonus2Min": 2,
    "attackPowerBonus2Max": 2,
    "durabilityBase": 80,
    "durabilityBonusMin": 9,
    "durabilityBonusMax": 17,
    "durabilityBonus2Min": 18,
    "durabilityBonus2Max": 41,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Kilton's Shop"
    ]
  },
  {
    "id": 7,
    "name": "Traveler's Sword",
    "cssClassName": null,
    "attackPowerBase": 5,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 8,
    "durabilityBase": 20,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 3,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Field",
      "West Necluda"
    ]
  },
  {
    "id": 8,
    "name": "Soldier's Broadsword",
    "cssClassName": null,
    "attackPowerBase": 14,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 11,
    "durabilityBase": 23,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 3,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Gerudo Desert",
      "Tabantha Frontier"
    ]
  },
  {
    "id": 9,
    "name": "Knight's Broadsword",
    "cssClassName": null,
    "attackPowerBase": 26,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 9,
    "durabilityBase": 27,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 8,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Gerudo Desert",
      "Tabantha Frontier"
    ]
  },
  {
    "id": 10,
    "name": "Royal Broadsword",
    "cssClassName": null,
    "attackPowerBase": 36,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 12,
    "attackPowerBonus2Min": 13,
    "attackPowerBonus2Max": 24,
    "durabilityBase": 36,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Tabantha Frontier",
      "Akkala Highlands",
      "Hyrule Castle"
    ]
  },
  {
    "id": 11,
    "name": "Forest Dweller's Sword",
    "cssClassName": null,
    "attackPowerBase": 22,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 8,
    "durabilityBase": 27,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 14,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Great Hyrule Forest",
      "Hyrule Field"
    ]
  },
  {
    "id": 12,
    "name": "Zora's Sword",
    "cssClassName": null,
    "attackPowerBase": 15,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 12,
    "durabilityBase": 27,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 14,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Lanayru Great Spring",
      "East Necluda"
    ]
  },
  {
    "id": 13,
    "name": "Feathered Edge",
    "cssClassName": null,
    "attackPowerBase": 15,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 12,
    "durabilityBase": 27,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 14,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Tabantha Frontier",
      "Hyrule Field"
    ]
  },
  {
    "id": 14,
    "name": "Gerudo Scimitar",
    "cssClassName": null,
    "attackPowerBase": 16,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 8,
    "durabilityBase": 23,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 12,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Gerudo Highlands",
      "Gerudo Desert"
    ]
  },
  {
    "id": 15,
    "name": "Moonlight Scimitar",
    "cssClassName": null,
    "attackPowerBase": 25,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 6,
    "durabilityBase": 52,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Gerudo Highlands",
      "Gerudo Desert"
    ]
  },
  {
    "id": 16,
    "name": "Scimitar of the Seven",
    "cssClassName": null,
    "attackPowerBase": 32,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 10,
    "durabilityBase": 60,
    "durabilityBonusMin": 6,
    "durabilityBonusMax": 12,
    "durabilityBonus2Min": 13,
    "durabilityBonus2Max": 30,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Reward for clearing Divine Beast Vah Naboris dungeon"
    ]
  },
  {
    "id": 17,
    "name": "Eightfold Blade",
    "cssClassName": null,
    "attackPowerBase": 15,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 12,
    "durabilityBase": 26,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 13,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "West Necluda",
      "Lake Hylia"
    ]
  },
  {
    "id": 18,
    "name": "Ancient Short Sword",
    "cssClassName": null,
    "attackPowerBase": 40,
    "attackPowerBonusMin": 7,
    "attackPowerBonusMax": 14,
    "attackPowerBonus2Min": 15,
    "attackPowerBonus2Max": 27,
    "durabilityBase": 54,
    "durabilityBonusMin": 6,
    "durabilityBonusMax": 11,
    "durabilityBonus2Min": 12,
    "durabilityBonus2Max": 27,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Akkala Ancient Tech Lab"
    ]
  },
  {
    "id": 19,
    "name": "Rusty Broadsword",
    "cssClassName": null,
    "attackPowerBase": 6,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 10,
    "durabilityBase": 8,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 4,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Field",
      "Eldin Canyon",
      "Hyrule Castle"
    ]
  },
  {
    "id": 20,
    "name": "Royal Guard's Sword",
    "cssClassName": null,
    "attackPowerBase": 48,
    "attackPowerBonusMin": 9,
    "attackPowerBonusMax": 16,
    "attackPowerBonus2Min": 17,
    "attackPowerBonus2Max": 33,
    "durabilityBase": 14,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Castle"
    ]
  },
  {
    "id": 21,
    "name": "Flameblade",
    "cssClassName": null,
    "attackPowerBase": 24,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 9,
    "attackPowerBonus2Min": 10,
    "attackPowerBonus2Max": 19,
    "durabilityBase": 36,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Coliseum Ruins",
      "East Necluda"
    ]
  },
  {
    "id": 22,
    "name": "Frostblade",
    "cssClassName": null,
    "attackPowerBase": 20,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 16,
    "durabilityBase": 30,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Gerudo Highlands",
      "Coliseum Ruins"
    ]
  },
  {
    "id": 23,
    "name": "Thunderblade",
    "cssClassName": null,
    "attackPowerBase": 22,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 18,
    "durabilityBase": 36,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Coliseum Ruins",
      "West Necluda"
    ]
  },
  {
    "id": 24,
    "name": "Goddess Sword",
    "cssClassName": null,
    "attackPowerBase": 28,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 10,
    "attackPowerBonus2Min": 11,
    "attackPowerBonus2Max": 17,
    "durabilityBase": 45,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 23,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Unlocked by corresponding amiibo"
    ]
  },
  {
    "id": 25,
    "name": "Sword",
    "cssClassName": null,
    "attackPowerBase": 22,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 14,
    "durabilityBase": 27,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 14,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Unlocked by corresponding amiibo"
    ]
  },
  {
    "id": 26,
    "name": "Sea Breeze Boomerang",
    "cssClassName": null,
    "attackPowerBase": 20,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 7,
    "attackPowerBonus2Min": 8,
    "attackPowerBonus2Max": 12,
    "durabilityBase": 20,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 10,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 20,
    "throwDistanceMin": 0.0,
    "throwDistanceMax": 0.0,
    "availabilities": [
      "Unlocked by corresponding amiibo"
    ]
  },
  {
    "id": 27,
    "name": "Boko Club",
    "cssClassName": null,
    "attackPowerBase": 4,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 7,
    "durabilityBase": 12,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 6,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Field",
      "West Necluda"
    ]
  },
  {
    "id": 28,
    "name": "Spiked Boko Club",
    "cssClassName": null,
    "attackPowerBase": 12,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 11,
    "durabilityBase": 14,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Faron Grasslands",
      "East Necluda"
    ]
  },
  {
    "id": 29,
    "name": "Dragonbone Boko Club",
    "cssClassName": null,
    "attackPowerBase": 24,
    "attackPowerBonusMin": 7,
    "attackPowerBonusMax": 13,
    "attackPowerBonus2Min": 14,
    "attackPowerBonus2Max": 26,
    "durabilityBase": 18,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Ridge",
      "Necluda Sea"
    ]
  },
  {
    "id": 30,
    "name": "Lizal Boomerang",
    "cssClassName": null,
    "attackPowerBase": 14,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 9,
    "durabilityBase": 17,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 0.0,
    "throwDistanceMax": 0.0,
    "availabilities": [
      "Lake Hylia",
      "Lanayru"
    ]
  },
  {
    "id": 31,
    "name": "Lizal Forked Boomerang",
    "cssClassName": null,
    "attackPowerBase": 24,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 11,
    "durabilityBase": 23,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 12,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 0.0,
    "throwDistanceMax": 0.0,
    "availabilities": [
      "Gerudo Desert",
      "Tabantha Frontier"
    ]
  },
  {
    "id": 32,
    "name": "Lizal Tri-Boomerang",
    "cssClassName": null,
    "attackPowerBase": 36,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 12,
    "attackPowerBonus2Min": 13,
    "attackPowerBonus2Max": 24,
    "durabilityBase": 27,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 14,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 0.0,
    "throwDistanceMax": 0.0,
    "availabilities": [
      "Hebra Mountains",
      "Akkala Highlands"
    ]
  },
  {
    "id": 33,
    "name": "Guardian Sword",
    "cssClassName": null,
    "attackPowerBase": 20,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 9,
    "durabilityBase": 17,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by Guardian Scout II"
    ]
  },
  {
    "id": 34,
    "name": "Guardian Sword+",
    "cssClassName": null,
    "attackPowerBase": 30,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 9,
    "durabilityBase": 26,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 13,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by Guardian Scout III"
    ]
  },
  {
    "id": 35,
    "name": "Guardian Sword++",
    "cssClassName": null,
    "attackPowerBase": 40,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 10,
    "attackPowerBonus2Min": 11,
    "attackPowerBonus2Max": 20,
    "durabilityBase": 32,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by Guardian Scout IV"
    ]
  },
  {
    "id": 36,
    "name": "Lynel Sword",
    "cssClassName": null,
    "attackPowerBase": 24,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 11,
    "durabilityBase": 17,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by Lynels"
    ]
  },
  {
    "id": 37,
    "name": "Mighty Lynel Sword",
    "cssClassName": null,
    "attackPowerBase": 36,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 11,
    "attackPowerBonus2Min": 12,
    "attackPowerBonus2Max": 21,
    "durabilityBase": 32,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by Blue-Maned Lynels"
    ]
  },
  {
    "id": 38,
    "name": "Savage Lynel Sword",
    "cssClassName": null,
    "attackPowerBase": 58,
    "attackPowerBonusMin": 11,
    "attackPowerBonusMax": 21,
    "attackPowerBonus2Min": 22,
    "attackPowerBonus2Max": 42,
    "durabilityBase": 41,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 21,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by White-Maned Lynels",
      "Silver Lynels"
    ]
  },
  {
    "id": 39,
    "name": "Fire Rod",
    "cssClassName": null,
    "attackPowerBase": 5,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 8,
    "durabilityBase": 14,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "1 fire ball",
    "throwDistanceBase": 30,
    "throwDistanceMin": 0.0,
    "throwDistanceMax": 0.0,
    "availabilities": [
      "Gerudo Highlands",
      "Great Hyrule Forest"
    ]
  },
  {
    "id": 40,
    "name": "Meteor Rod",
    "cssClassName": null,
    "attackPowerBase": 10,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 16,
    "durabilityBase": 32,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "3 fire balls",
    "throwDistanceBase": 30,
    "throwDistanceMin": 0.0,
    "throwDistanceMax": 0.0,
    "availabilities": [
      "Crenel Hills",
      "Hebra Mountains"
    ]
  },
  {
    "id": 41,
    "name": "Ice Rod",
    "cssClassName": null,
    "attackPowerBase": 5,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 8,
    "durabilityBase": 14,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "1 ice ball",
    "throwDistanceBase": 30,
    "throwDistanceMin": 0.0,
    "throwDistanceMax": 0.0,
    "availabilities": [
      "Gerudo Highlands",
      "Eldin Canyon"
    ]
  },
  {
    "id": 42,
    "name": "Blizzard Rod",
    "cssClassName": null,
    "attackPowerBase": 10,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 16,
    "durabilityBase": 32,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "3 ice balls",
    "throwDistanceBase": 30,
    "throwDistanceMin": 0.0,
    "throwDistanceMax": 0.0,
    "availabilities": [
      "Gerudo Highlands",
      "Hebra Mountains",
      "Crenel Hills"
    ]
  },
  {
    "id": 43,
    "name": "Lightning Rod",
    "cssClassName": null,
    "attackPowerBase": 5,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 8,
    "durabilityBase": 14,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "1 electric ball",
    "throwDistanceBase": 30,
    "throwDistanceMin": 0.0,
    "throwDistanceMax": 0.0,
    "availabilities": [
      "West Necluda",
      "Hyrule Ridge"
    ]
  },
  {
    "id": 44,
    "name": "Thunderstorm Rod",
    "cssClassName": null,
    "attackPowerBase": 10,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 16,
    "durabilityBase": 32,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "3 electric balls",
    "throwDistanceBase": 30,
    "throwDistanceMin": 0.0,
    "throwDistanceMax": 0.0,
    "availabilities": [
      "Crenel Hills",
      "Hyrule Ridge"
    ]
  },
  {
    "id": 45,
    "name": "Vicious Sickle",
    "cssClassName": null,
    "attackPowerBase": 16,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 13,
    "durabilityBase": 14,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 6,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by Yiga Footsoldiers"
    ]
  },
  {
    "id": 46,
    "name": "Demon Carver",
    "cssClassName": null,
    "attackPowerBase": 40,
    "attackPowerBonusMin": 7,
    "attackPowerBonusMax": 14,
    "attackPowerBonus2Min": 15,
    "attackPowerBonus2Max": 27,
    "durabilityBase": 25,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 12,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by Yiga Footsoldiers"
    ]
  },
  {
    "id": 47,
    "name": "Bokoblin Arm",
    "cssClassName": null,
    "attackPowerBase": 5,
    "attackPowerBonusMin": 1,
    "attackPowerBonusMax": 2,
    "attackPowerBonus2Min": 3,
    "attackPowerBonus2Max": 5,
    "durabilityBase": 5,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 5,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by Stalkoblins"
    ]
  },
  {
    "id": 48,
    "name": "Lizalfos Arm",
    "cssClassName": null,
    "attackPowerBase": 12,
    "attackPowerBonusMin": 1,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 8,
    "durabilityBase": 8,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 8,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 0.0,
    "throwDistanceMax": 0.0,
    "availabilities": [
      "Dropped by Stalizalfos"
    ]
  },
  {
    "id": 49,
    "name": "Korok Leaf",
    "cssClassName": null,
    "attackPowerBase": 1,
    "attackPowerBonusMin": 0,
    "attackPowerBonusMax": 0,
    "attackPowerBonus2Min": 0,
    "attackPowerBonus2Max": 0,
    "durabilityBase": 25,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 12,
    "throwDistanceEffect": "Wind gust",
    "throwDistanceBase": 5,
    "throwDistanceMin": 0.0,
    "throwDistanceMax": 0.0,
    "availabilities": [
      "Hyrule Field",
      "West Necluda"
    ]
  },
  {
    "id": 50,
    "name": "Farming Hoe",
    "cssClassName": null,
    "attackPowerBase": 16,
    "attackPowerBonusMin": 8,
    "attackPowerBonusMax": 14,
    "attackPowerBonus2Min": 15,
    "attackPowerBonus2Max": 20,
    "durabilityBase": 6,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 3,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Field",
      "West Necluda"
    ]
  },
  {
    "id": 51,
    "name": "Boat Oar",
    "cssClassName": null,
    "attackPowerBase": 14,
    "attackPowerBonusMin": 7,
    "attackPowerBonusMax": 13,
    "attackPowerBonus2Min": 14,
    "attackPowerBonus2Max": 26,
    "durabilityBase": 8,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 4,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "East Necluda",
      "Necluda Sea"
    ]
  },
  {
    "id": 52,
    "name": "Woodcutter's Axe",
    "cssClassName": null,
    "attackPowerBase": 3,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 6,
    "durabilityBase": 47,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "At various stables"
    ]
  },
  {
    "id": 53,
    "name": "Double Axe",
    "cssClassName": null,
    "attackPowerBase": 18,
    "attackPowerBonusMin": 9,
    "attackPowerBonusMax": 16,
    "attackPowerBonus2Min": 17,
    "attackPowerBonus2Max": 22,
    "durabilityBase": 52,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 21,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "At various stables"
    ]
  },
  {
    "id": 54,
    "name": "Iron Sledgehammer",
    "cssClassName": null,
    "attackPowerBase": 12,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 11,
    "attackPowerBonus2Min": 12,
    "attackPowerBonus2Max": 22,
    "durabilityBase": 40,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Eldin Canyon",
      "Akkala Highlands",
      "Tanagar Canyon Course"
    ]
  },
  {
    "id": 55,
    "name": "Giant Boomerang",
    "cssClassName": null,
    "attackPowerBase": 25,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 11,
    "attackPowerBonus2Min": 12,
    "attackPowerBonus2Max": 22,
    "durabilityBase": 40,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 0.0,
    "throwDistanceMax": 0.0,
    "availabilities": [
      "West Necluda",
      "Hebra Mountains"
    ]
  },
  {
    "id": 56,
    "name": "Traveler's Claymore",
    "cssClassName": null,
    "attackPowerBase": 10,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 9,
    "durabilityBase": 20,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 4,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Field",
      "West Necluda"
    ]
  },
  {
    "id": 57,
    "name": "Soldier's Claymore",
    "cssClassName": null,
    "attackPowerBase": 20,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 9,
    "attackPowerBonus2Min": 10,
    "attackPowerBonus2Max": 17,
    "durabilityBase": 25,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 3,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Field",
      "Faron Grasslands"
    ]
  },
  {
    "id": 58,
    "name": "Knight's Claymore",
    "cssClassName": null,
    "attackPowerBase": 38,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 7,
    "attackPowerBonus2Min": 8,
    "attackPowerBonus2Max": 13,
    "durabilityBase": 30,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 8,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Gerudo Desert",
      "Tabantha Frontier"
    ]
  },
  {
    "id": 59,
    "name": "Royal Claymore",
    "cssClassName": null,
    "attackPowerBase": 52,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 10,
    "attackPowerBonus2Min": 11,
    "attackPowerBonus2Max": 20,
    "durabilityBase": 40,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Gerudo Desert",
      "Tabantha Frontier",
      "Hyrule Castle"
    ]
  },
  {
    "id": 60,
    "name": "Silver Longsword",
    "cssClassName": null,
    "attackPowerBase": 22,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 19,
    "durabilityBase": 30,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 14,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Lanayru Great Spring",
      "Lanayru Wetlands"
    ]
  },
  {
    "id": 61,
    "name": "Cobble Crusher",
    "cssClassName": null,
    "attackPowerBase": 15,
    "attackPowerBonusMin": 7,
    "attackPowerBonusMax": 14,
    "attackPowerBonus2Min": 15,
    "attackPowerBonus2Max": 26,
    "durabilityBase": 30,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 14,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Eldin Canyon",
      "Eldin Mountains"
    ]
  },
  {
    "id": 62,
    "name": "Stone Smasher",
    "cssClassName": null,
    "attackPowerBase": 42,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 9,
    "attackPowerBonus2Min": 10,
    "attackPowerBonus2Max": 17,
    "durabilityBase": 40,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Eldin Canyon",
      "Hyrule Field"
    ]
  },
  {
    "id": 63,
    "name": "Boulder Breaker",
    "cssClassName": null,
    "attackPowerBase": 60,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 15,
    "durabilityBase": 60,
    "durabilityBonusMin": 6,
    "durabilityBonusMax": 11,
    "durabilityBonus2Min": 12,
    "durabilityBonus2Max": 27,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Reward for clearing Divine Beast Vah Rudania dungeon"
    ]
  },
  {
    "id": 64,
    "name": "Golden Claymore",
    "cssClassName": null,
    "attackPowerBase": 28,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 15,
    "durabilityBase": 30,
    "durabilityBonusMin": 6,
    "durabilityBonusMax": 11,
    "durabilityBonus2Min": 12,
    "durabilityBonus2Max": 27,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Gerudo Highlands",
      "Hyrule Ridge"
    ]
  },
  {
    "id": 65,
    "name": "Eightfold Longblade",
    "cssClassName": null,
    "attackPowerBase": 32,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 11,
    "durabilityBase": 25,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 12,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "West Necluda",
      "Lanayru Great Spring"
    ]
  },
  {
    "id": 66,
    "name": "Edge of Duality",
    "cssClassName": null,
    "attackPowerBase": 50,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 10,
    "attackPowerBonus2Min": 11,
    "attackPowerBonus2Max": 19,
    "durabilityBase": 35,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Field",
      "West Necluda"
    ]
  },
  {
    "id": 67,
    "name": "Ancient Bladesaw",
    "cssClassName": null,
    "attackPowerBase": 55,
    "attackPowerBonusMin": 11,
    "attackPowerBonusMax": 20,
    "attackPowerBonus2Min": 21,
    "attackPowerBonus2Max": 33,
    "durabilityBase": 50,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 23,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Akkala Ancient Tech Lab"
    ]
  },
  {
    "id": 68,
    "name": "Rusty Claymore",
    "cssClassName": null,
    "attackPowerBase": 12,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 11,
    "attackPowerBonus2Min": 12,
    "attackPowerBonus2Max": 22,
    "durabilityBase": 10,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 5,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Field",
      "Eldin Canyon",
      "Hyrule Castle"
    ]
  },
  {
    "id": 69,
    "name": "Royal Guard's Claymore",
    "cssClassName": null,
    "attackPowerBase": 72,
    "attackPowerBonusMin": 14,
    "attackPowerBonusMax": 26,
    "attackPowerBonus2Min": 27,
    "attackPowerBonus2Max": 44,
    "durabilityBase": 15,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 35,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Castle"
    ]
  },
  {
    "id": 70,
    "name": "Great Flameblade",
    "cssClassName": null,
    "attackPowerBase": 34,
    "attackPowerBonusMin": 7,
    "attackPowerBonusMax": 12,
    "attackPowerBonus2Min": 13,
    "attackPowerBonus2Max": 21,
    "durabilityBase": 50,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 15,
    "durabilityBonus2Min": 16,
    "durabilityBonus2Max": 30,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Coliseum Ruins",
      "Eldin Canyon"
    ]
  },
  {
    "id": 71,
    "name": "Great Frostblade",
    "cssClassName": null,
    "attackPowerBase": 30,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 11,
    "attackPowerBonus2Min": 12,
    "attackPowerBonus2Max": 18,
    "durabilityBase": 40,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 15,
    "durabilityBonus2Min": 16,
    "durabilityBonus2Max": 30,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Coliseum Ruins",
      "Hebra Mountains"
    ]
  },
  {
    "id": 72,
    "name": "Great Thunderblade",
    "cssClassName": null,
    "attackPowerBase": 32,
    "attackPowerBonusMin": 7,
    "attackPowerBonusMax": 12,
    "attackPowerBonus2Min": 13,
    "attackPowerBonus2Max": 20,
    "durabilityBase": 50,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 15,
    "durabilityBonus2Min": 16,
    "durabilityBonus2Max": 30,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Coliseum Ruins",
      "Tabantha Frontier"
    ]
  },
  {
    "id": 73,
    "name": "Sword of the Six Sages",
    "cssClassName": null,
    "attackPowerBase": 48,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 10,
    "attackPowerBonus2Min": 11,
    "attackPowerBonus2Max": 19,
    "durabilityBase": 50,
    "durabilityBonusMin": 8,
    "durabilityBonusMax": 25,
    "durabilityBonus2Min": 26,
    "durabilityBonus2Max": 43,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Unlocked by corresponding amiibo"
    ]
  },
  {
    "id": 74,
    "name": "Biggoron's Sword",
    "cssClassName": null,
    "attackPowerBase": 50,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 10,
    "attackPowerBonus2Min": 11,
    "attackPowerBonus2Max": 19,
    "durabilityBase": 60,
    "durabilityBonusMin": 9,
    "durabilityBonusMax": 30,
    "durabilityBonus2Min": 31,
    "durabilityBonus2Max": 51,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Unlocked by corresponding amiibo"
    ]
  },
  {
    "id": 75,
    "name": "Fierce Deity Sword",
    "cssClassName": null,
    "attackPowerBase": 60,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 12,
    "attackPowerBonus2Min": 13,
    "attackPowerBonus2Max": 23,
    "durabilityBase": 35,
    "durabilityBonusMin": 6,
    "durabilityBonusMax": 18,
    "durabilityBonus2Min": 19,
    "durabilityBonus2Max": 30,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Unlocked by corresponding amiibo"
    ]
  },
  {
    "id": 76,
    "name": "Boko Bat",
    "cssClassName": null,
    "attackPowerBase": 6,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 11,
    "durabilityBase": 8,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 4,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Field",
      "West Necluda"
    ]
  },
  {
    "id": 77,
    "name": "Spiked Boko Bat",
    "cssClassName": null,
    "attackPowerBase": 18,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 9,
    "attackPowerBonus2Min": 10,
    "attackPowerBonus2Max": 17,
    "durabilityBase": 12,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 6,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Faron Grasslands",
      "East Necluda"
    ]
  },
  {
    "id": 78,
    "name": "Dragonbone Boko Bat",
    "cssClassName": null,
    "attackPowerBase": 36,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 12,
    "attackPowerBonus2Min": 13,
    "attackPowerBonus2Max": 24,
    "durabilityBase": 16,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 8,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Ridge",
      "Necluda Sea"
    ]
  },
  {
    "id": 79,
    "name": "Moblin Club",
    "cssClassName": null,
    "attackPowerBase": 9,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 9,
    "attackPowerBonus2Min": 10,
    "attackPowerBonus2Max": 17,
    "durabilityBase": 12,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 6,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Field",
      "West Necluda"
    ]
  },
  {
    "id": 80,
    "name": "Spiked Moblin Club",
    "cssClassName": null,
    "attackPowerBase": 27,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 9,
    "attackPowerBonus2Min": 10,
    "attackPowerBonus2Max": 17,
    "durabilityBase": 18,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Field",
      "Akkala Highlands"
    ]
  },
  {
    "id": 81,
    "name": "Dragonbone Moblin Club",
    "cssClassName": null,
    "attackPowerBase": 36,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 12,
    "attackPowerBonus2Min": 13,
    "attackPowerBonus2Max": 24,
    "durabilityBase": 16,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 8,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Ridge",
      "Necluda Sea"
    ]
  },
  {
    "id": 82,
    "name": "Ancient Battle Axe",
    "cssClassName": null,
    "attackPowerBase": 30,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 14,
    "durabilityBase": 15,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by Guardian Scout II"
    ]
  },
  {
    "id": 83,
    "name": "Ancient Battle Axe+",
    "cssClassName": null,
    "attackPowerBase": 45,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 14,
    "durabilityBase": 20,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by Guardian Scout III"
    ]
  },
  {
    "id": 84,
    "name": "Ancient Battle Axe++",
    "cssClassName": null,
    "attackPowerBase": 60,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 15,
    "durabilityBase": 25,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 12,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by Guardian Scout IV"
    ]
  },
  {
    "id": 85,
    "name": "Lynel Crusher",
    "cssClassName": null,
    "attackPowerBase": 36,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 9,
    "attackPowerBonus2Min": 10,
    "attackPowerBonus2Max": 17,
    "durabilityBase": 20,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by Lynels"
    ]
  },
  {
    "id": 86,
    "name": "Mighty Lynel Crusher",
    "cssClassName": null,
    "attackPowerBase": 54,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 12,
    "attackPowerBonus2Min": 13,
    "attackPowerBonus2Max": 23,
    "durabilityBase": 25,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 12,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by Blue-Maned Lynels"
    ]
  },
  {
    "id": 87,
    "name": "Savage Lynel Crusher",
    "cssClassName": null,
    "attackPowerBase": 78,
    "attackPowerBonusMin": 8,
    "attackPowerBonusMax": 15,
    "attackPowerBonus2Min": 16,
    "attackPowerBonus2Max": 30,
    "durabilityBase": 35,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by White-Maned Lynels",
      "Silver Lynels"
    ]
  },
  {
    "id": 88,
    "name": "Windcleaver",
    "cssClassName": null,
    "attackPowerBase": 40,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 14,
    "durabilityBase": 25,
    "durabilityBonusMin": 6,
    "durabilityBonusMax": 15,
    "durabilityBonus2Min": 16,
    "durabilityBonus2Max": 24,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 20,
    "throwDistanceMin": 1.0,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by Yiga Blademasters"
    ]
  },
  {
    "id": 89,
    "name": "Moblin Arm",
    "cssClassName": null,
    "attackPowerBase": 15,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 13,
    "durabilityBase": 5,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 20,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by Stalmoblins"
    ]
  },
  {
    "id": 90,
    "name": "Wooden Mop",
    "cssClassName": null,
    "attackPowerBase": 5,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 5,
    "durabilityBase": 8,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 4,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "East Necluda",
      "Hyrule Field"
    ]
  },
  {
    "id": 91,
    "name": "Farmer's Pitchfork",
    "cssClassName": null,
    "attackPowerBase": 7,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 6,
    "durabilityBase": 12,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 6,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "East Necluda",
      "West Necluda"
    ]
  },
  {
    "id": 92,
    "name": "Fishing Harpoon",
    "cssClassName": null,
    "attackPowerBase": 8,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 6,
    "durabilityBase": 12,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 6,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "East Necluda",
      "Lake Hylia"
    ]
  },
  {
    "id": 93,
    "name": "Throwing Spear",
    "cssClassName": null,
    "attackPowerBase": 6,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 12,
    "durabilityBase": 20,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "West Necluda",
      "Hyrule Field"
    ]
  },
  {
    "id": 94,
    "name": "Traveler's Spear",
    "cssClassName": null,
    "attackPowerBase": 3,
    "attackPowerBonusMin": 1,
    "attackPowerBonusMax": 2,
    "attackPowerBonus2Min": 3,
    "attackPowerBonus2Max": 3,
    "durabilityBase": 30,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 4,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "West Necluda",
      "Hyrule Field"
    ]
  },
  {
    "id": 95,
    "name": "Soldier's Spear",
    "cssClassName": null,
    "attackPowerBase": 7,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 5,
    "durabilityBase": 35,
    "durabilityBonusMin": 1,
    "durabilityBonusMax": 2,
    "durabilityBonus2Min": 3,
    "durabilityBonus2Max": 3,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Field",
      "Faron Grasslands"
    ]
  },
  {
    "id": 96,
    "name": "Knight's Halberd",
    "cssClassName": null,
    "attackPowerBase": 13,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 7,
    "attackPowerBonus2Min": 8,
    "attackPowerBonus2Max": 12,
    "durabilityBase": 40,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 8,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Tabantha Frontier",
      "Gerudo Desert"
    ]
  },
  {
    "id": 97,
    "name": "Royal Halberd",
    "cssClassName": null,
    "attackPowerBase": 26,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 10,
    "attackPowerBonus2Min": 11,
    "attackPowerBonus2Max": 20,
    "durabilityBase": 50,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 15,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Gerudo Highlands",
      "Tabantha Frontier"
    ]
  },
  {
    "id": 98,
    "name": "Forest Dweller's Spear",
    "cssClassName": null,
    "attackPowerBase": 11,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 6,
    "attackPowerBonus2Min": 7,
    "attackPowerBonus2Max": 11,
    "durabilityBase": 35,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Great Hyrule Forest",
      "Hyrule Ridge"
    ]
  },
  {
    "id": 99,
    "name": "Zora Spear",
    "cssClassName": null,
    "attackPowerBase": 9,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 7,
    "durabilityBase": 40,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Lanayru Great Spring",
      "Lake Hylia"
    ]
  },
  {
    "id": 100,
    "name": "Silverscale Spear",
    "cssClassName": null,
    "attackPowerBase": 12,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 7,
    "attackPowerBonus2Min": 8,
    "attackPowerBonus2Max": 12,
    "durabilityBase": 40,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 8,
    "durabilityBonus2Min": 9,
    "durabilityBonus2Max": 18,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Akkala Highlands",
      "Lanayru Great Spring"
    ]
  },
  {
    "id": 101,
    "name": "Ceremonial Trident",
    "cssClassName": null,
    "attackPowerBase": 14,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 13,
    "durabilityBase": 40,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 14,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Zora's Domain"
    ]
  },
  {
    "id": 102,
    "name": "Lightscale Trident",
    "cssClassName": null,
    "attackPowerBase": 22,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 9,
    "attackPowerBonus2Min": 10,
    "attackPowerBonus2Max": 18,
    "durabilityBase": 70,
    "durabilityBonusMin": 7,
    "durabilityBonusMax": 13,
    "durabilityBonus2Min": 14,
    "durabilityBonus2Max": 32,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Reward for clearing Divine Beast Vah Ruta dungeon"
    ]
  },
  {
    "id": 103,
    "name": "Drillshaft",
    "cssClassName": null,
    "attackPowerBase": 14,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 13,
    "durabilityBase": 50,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 23,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Eldin Canyon",
      "Hebra Mountains"
    ]
  },
  {
    "id": 104,
    "name": "Feathered Spear",
    "cssClassName": null,
    "attackPowerBase": 10,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 8,
    "durabilityBase": 35,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Tabantha Frontier",
      "Hyrule Field"
    ]
  },
  {
    "id": 105,
    "name": "Gerudo Spear",
    "cssClassName": null,
    "attackPowerBase": 16,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 9,
    "attackPowerBonus2Min": 10,
    "attackPowerBonus2Max": 15,
    "durabilityBase": 35,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Gerudo Highlands",
      "Gerudo Desert"
    ]
  },
  {
    "id": 106,
    "name": "Serpentine Spear",
    "cssClassName": null,
    "attackPowerBase": 12,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 7,
    "attackPowerBonus2Min": 8,
    "attackPowerBonus2Max": 12,
    "durabilityBase": 35,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "East Necluda",
      "Hyrule Field"
    ]
  },
  {
    "id": 107,
    "name": "Ancient Spear",
    "cssClassName": null,
    "attackPowerBase": 30,
    "attackPowerBonusMin": 6,
    "attackPowerBonusMax": 12,
    "attackPowerBonus2Min": 13,
    "attackPowerBonus2Max": 24,
    "durabilityBase": 50,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 23,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Akkala Ancient Tech Lab"
    ]
  },
  {
    "id": 108,
    "name": "Rusty Halberd",
    "cssClassName": null,
    "attackPowerBase": 5,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 10,
    "durabilityBase": 15,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Field",
      "Great Hyrule Forest"
    ]
  },
  {
    "id": 109,
    "name": "Royal Guard's Spear",
    "cssClassName": null,
    "attackPowerBase": 32,
    "attackPowerBonusMin": 7,
    "attackPowerBonusMax": 13,
    "attackPowerBonus2Min": 14,
    "attackPowerBonus2Max": 25,
    "durabilityBase": 15,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hyrule Castle"
    ]
  },
  {
    "id": 110,
    "name": "Flamespear",
    "cssClassName": null,
    "attackPowerBase": 24,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 10,
    "attackPowerBonus2Min": 11,
    "attackPowerBonus2Max": 19,
    "durabilityBase": 50,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 23,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Coliseum Ruins",
      "Hebra Mountains"
    ]
  },
  {
    "id": 111,
    "name": "Frostspear",
    "cssClassName": null,
    "attackPowerBase": 20,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 8,
    "attackPowerBonus2Min": 9,
    "attackPowerBonus2Max": 16,
    "durabilityBase": 40,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 23,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Coliseum Ruins",
      "Hebra Mountains"
    ]
  },
  {
    "id": 112,
    "name": "Thunderspear",
    "cssClassName": null,
    "attackPowerBase": 22,
    "attackPowerBonusMin": 5,
    "attackPowerBonusMax": 9,
    "attackPowerBonus2Min": 10,
    "attackPowerBonus2Max": 18,
    "durabilityBase": 50,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 23,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Coliseum Ruins",
      "Hyrule Ridge"
    ]
  },
  {
    "id": 113,
    "name": "Boko Spear",
    "cssClassName": null,
    "attackPowerBase": 2,
    "attackPowerBonusMin": 1,
    "attackPowerBonusMax": 2,
    "attackPowerBonus2Min": 3,
    "attackPowerBonus2Max": 3,
    "durabilityBase": 12,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 6,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "West Necluda",
      "Hyrule Field"
    ]
  },
  {
    "id": 114,
    "name": "Spiked Boko Spear",
    "cssClassName": null,
    "attackPowerBase": 6,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 5,
    "durabilityBase": 15,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Faron Grasslands",
      "East Necluda"
    ]
  },
  {
    "id": 115,
    "name": "Dragonbone Boko Spear",
    "cssClassName": null,
    "attackPowerBase": 12,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 7,
    "durabilityBase": 20,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Necluda Sea",
      "Hyrule Ridge"
    ]
  },
  {
    "id": 116,
    "name": "Moblin Spear",
    "cssClassName": null,
    "attackPowerBase": 4,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 4,
    "durabilityBase": 15,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 3,
    "durabilityBonus2Min": 4,
    "durabilityBonus2Max": 7,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Faron Grasslands",
      "Gerudo Highlands"
    ]
  },
  {
    "id": 117,
    "name": "Spiked Moblin Spear",
    "cssClassName": null,
    "attackPowerBase": 9,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 5,
    "durabilityBase": 20,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Gerudo Highlands",
      "Akkala Highlands"
    ]
  },
  {
    "id": 118,
    "name": "Dragonbone Moblin Spear",
    "cssClassName": null,
    "attackPowerBase": 15,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 7,
    "durabilityBase": 25,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 12,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Hebra Mountains",
      "Eldin Mountains"
    ]
  },
  {
    "id": 119,
    "name": "Lizal Spear",
    "cssClassName": null,
    "attackPowerBase": 7,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 4,
    "durabilityBase": 18,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Lanayru Wetlands",
      "East Necluda"
    ]
  },
  {
    "id": 120,
    "name": "Enhanced Lizal Spear",
    "cssClassName": null,
    "attackPowerBase": 12,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 5,
    "durabilityBase": 22,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 10,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Tabantha Frontier",
      "Gerudo Desert"
    ]
  },
  {
    "id": 121,
    "name": "Forked Lizal Spear",
    "cssClassName": null,
    "attackPowerBase": 18,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 7,
    "durabilityBase": 28,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 6,
    "durabilityBonus2Min": 7,
    "durabilityBonus2Max": 13,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Eldin Canyon",
      "Akkala Highlands"
    ]
  },
  {
    "id": 122,
    "name": "Guardian Spear",
    "cssClassName": null,
    "attackPowerBase": 10,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 4,
    "durabilityBase": 20,
    "durabilityBonusMin": 2,
    "durabilityBonusMax": 4,
    "durabilityBonus2Min": 5,
    "durabilityBonus2Max": 9,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by Guardian Scout II"
    ]
  },
  {
    "id": 123,
    "name": "Guardian Spear+",
    "cssClassName": null,
    "attackPowerBase": 15,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 4,
    "durabilityBase": 25,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 12,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by Guardian Scout III"
    ]
  },
  {
    "id": 124,
    "name": "Guardian Spear++",
    "cssClassName": null,
    "attackPowerBase": 20,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 4,
    "attackPowerBonus2Min": 5,
    "attackPowerBonus2Max": 8,
    "durabilityBase": 35,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by Guardian Scout IV"
    ]
  },
  {
    "id": 125,
    "name": "Lynel Spear",
    "cssClassName": null,
    "attackPowerBase": 14,
    "attackPowerBonusMin": 2,
    "attackPowerBonusMax": 3,
    "attackPowerBonus2Min": 4,
    "attackPowerBonus2Max": 5,
    "durabilityBase": 25,
    "durabilityBonusMin": 3,
    "durabilityBonusMax": 5,
    "durabilityBonus2Min": 6,
    "durabilityBonus2Max": 12,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by Lynels"
    ]
  },
  {
    "id": 126,
    "name": "Mighty Lynel Spear",
    "cssClassName": null,
    "attackPowerBase": 20,
    "attackPowerBonusMin": 3,
    "attackPowerBonusMax": 5,
    "attackPowerBonus2Min": 6,
    "attackPowerBonus2Max": 9,
    "durabilityBase": 35,
    "durabilityBonusMin": 4,
    "durabilityBonusMax": 7,
    "durabilityBonus2Min": 8,
    "durabilityBonus2Max": 16,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by Blue-Maned Lynels"
    ]
  },
  {
    "id": 127,
    "name": "Savage Lynel Spear",
    "cssClassName": null,
    "attackPowerBase": 30,
    "attackPowerBonusMin": 4,
    "attackPowerBonusMax": 7,
    "attackPowerBonus2Min": 8,
    "attackPowerBonus2Max": 14,
    "durabilityBase": 45,
    "durabilityBonusMin": 5,
    "durabilityBonusMax": 9,
    "durabilityBonus2Min": 10,
    "durabilityBonus2Max": 21,
    "throwDistanceEffect": "Weapon Thrown",
    "throwDistanceBase": 5,
    "throwDistanceMin": 1.5,
    "throwDistanceMax": 2.0,
    "availabilities": [
      "Dropped by White-Maned Lynels",
      "Silver Lynels"
    ]
  }
]